#!/bin/sh

# Convenience script for running SWIG before it is installed.
# Intended for ad-hoc usage and not by the test-suite or examples.

builddir=`dirname "$0"`
SWIG_LIB='/eden/forge/applet/tool/swig-4.0.0/Lib'
export SWIG_LIB
exec "$builddir/swig" "$@"
