-- This file is generated by SWIG. Please do *not* modify by hand.
--
with Interfaces.C.Pointers;
with Interfaces.C.Strings;
with System;
package swigg.Pointers is

   -- DOH_Pointer
   --
   type DOH_Pointer is access all swigg.DOH;

   -- DOH_Pointers
   --
   type DOH_Pointers is
     array
       (Interfaces.C.size_t range <>) of aliased swigg.Pointers.DOH_Pointer;

   -- DohObjInfo_Pointer
   --
   type DohObjInfo_Pointer is access all swigg.DohObjInfo;

   -- DohObjInfo_Pointers
   --
   type DohObjInfo_Pointers is
     array
       (Interfaces.C
          .size_t range <>) of aliased swigg.Pointers.DohObjInfo_Pointer;

   -- String_Pointer
   --
   type String_Pointer is access all swigg.String;

   -- String_Pointers
   --
   type String_Pointers is
     array
       (Interfaces.C.size_t range <>) of aliased swigg.Pointers.String_Pointer;

   -- Hash_Pointer
   --
   type Hash_Pointer is access all swigg.Hash;

   -- Hash_Pointers
   --
   type Hash_Pointers is
     array
       (Interfaces.C.size_t range <>) of aliased swigg.Pointers.Hash_Pointer;

   -- List_Pointer
   --
   type List_Pointer is access all swigg.List;

   -- List_Pointers
   --
   type List_Pointers is
     array
       (Interfaces.C.size_t range <>) of aliased swigg.Pointers.List_Pointer;

   -- String_or_char_Pointer
   --
   type String_or_char_Pointer is access all swigg.String_or_char;

   -- String_or_char_Pointers
   --
   type String_or_char_Pointers is
     array
       (Interfaces.C
          .size_t range <>) of aliased swigg.Pointers.String_or_char_Pointer;

   -- File_Pointer
   --
   type File_Pointer is access all swigg.File;

   -- File_Pointers
   --
   type File_Pointers is
     array
       (Interfaces.C.size_t range <>) of aliased swigg.Pointers.File_Pointer;

   -- Parm_Pointer
   --
   type Parm_Pointer is access all swigg.Parm;

   -- Parm_Pointers
   --
   type Parm_Pointers is
     array
       (Interfaces.C.size_t range <>) of aliased swigg.Pointers.Parm_Pointer;

   -- ParmList_Pointer
   --
   type ParmList_Pointer is access all swigg.ParmList;

   -- ParmList_Pointers
   --
   type ParmList_Pointers is
     array
       (Interfaces.C
          .size_t range <>) of aliased swigg.Pointers.ParmList_Pointer;

   -- Node_Pointer
   --
   type Node_Pointer is access all swigg.Node;

   -- Node_Pointers
   --
   type Node_Pointers is
     array
       (Interfaces.C.size_t range <>) of aliased swigg.Pointers.Node_Pointer;

   -- Symtab_Pointer
   --
   type Symtab_Pointer is access all swigg.Symtab;

   -- Symtab_Pointers
   --
   type Symtab_Pointers is
     array
       (Interfaces.C.size_t range <>) of aliased swigg.Pointers.Symtab_Pointer;

   -- Typetab_Pointer
   --
   type Typetab_Pointer is access all swigg.Typetab;

   -- Typetab_Pointers
   --
   type Typetab_Pointers is
     array
       (Interfaces.C
          .size_t range <>) of aliased swigg.Pointers.Typetab_Pointer;

   -- SwigType_Pointer
   --
   type SwigType_Pointer is access all swigg.SwigType;

   -- SwigType_Pointers
   --
   type SwigType_Pointers is
     array
       (Interfaces.C
          .size_t range <>) of aliased swigg.Pointers.SwigType_Pointer;

   -- ErrorMessageFormat_Pointer
   --
   type ErrorMessageFormat_Pointer is access all swigg.ErrorMessageFormat;

   -- ErrorMessageFormat_Pointers
   --
   type ErrorMessageFormat_Pointers is
     array
       (Interfaces.C
          .size_t range <>) of aliased swigg.Pointers
       .ErrorMessageFormat_Pointer;

end swigg.Pointers;
