-- This file is generated by SWIG. Please do *not* modify by hand.
--
with interfaces.C;

package swigg_module.Pointers is

   -- String_Pointer
   --
   type String_Pointer is access all swigg_module.String;

   -- String_Pointers
   --
   type String_Pointers is
     array
       (interfaces.C.Size_t range <>) of aliased swigg_module.Pointers
       .String_Pointer;

   -- Hash_Pointer
   --
   type Hash_Pointer is access all swigg_module.Hash;

   -- Hash_Pointers
   --
   type Hash_Pointers is
     array
       (interfaces.C.Size_t range <>) of aliased swigg_module.Pointers
       .Hash_Pointer;

   -- List_Pointer
   --
   type List_Pointer is access all swigg_module.List;

   -- List_Pointers
   --
   type List_Pointers is
     array
       (interfaces.C.Size_t range <>) of aliased swigg_module.Pointers
       .List_Pointer;

   -- String_or_char_Pointer
   --
   type String_or_char_Pointer is access all swigg_module.String_or_char;

   -- String_or_char_Pointers
   --
   type String_or_char_Pointers is
     array
       (interfaces.C.Size_t range <>) of aliased swigg_module.Pointers
       .String_or_char_Pointer;

   -- File_Pointer
   --
   type File_Pointer is access all swigg_module.File;

   -- File_Pointers
   --
   type File_Pointers is
     array
       (interfaces.C.Size_t range <>) of aliased swigg_module.Pointers
       .File_Pointer;

   -- Parm_Pointer
   --
   type Parm_Pointer is access all swigg_module.Parm;

   -- Parm_Pointers
   --
   type Parm_Pointers is
     array
       (interfaces.C.Size_t range <>) of aliased swigg_module.Pointers
       .Parm_Pointer;

   -- ParmList_Pointer
   --
   type ParmList_Pointer is access all swigg_module.ParmList;

   -- ParmList_Pointers
   --
   type ParmList_Pointers is
     array
       (interfaces.C.Size_t range <>) of aliased swigg_module.Pointers
       .ParmList_Pointer;

   -- Node_Pointer
   --
   type Node_Pointer is access all swigg_module.Node;

   -- Node_Pointers
   --
   type Node_Pointers is
     array
       (interfaces.C.Size_t range <>) of aliased swigg_module.Pointers
       .Node_Pointer;

   -- Symtab_Pointer
   --
   type Symtab_Pointer is access all swigg_module.Symtab;

   -- Symtab_Pointers
   --
   type Symtab_Pointers is
     array
       (interfaces.C.Size_t range <>) of aliased swigg_module.Pointers
       .Symtab_Pointer;

   -- Typetab_Pointer
   --
   type Typetab_Pointer is access all swigg_module.Typetab;

   -- Typetab_Pointers
   --
   type Typetab_Pointers is
     array
       (interfaces.C.Size_t range <>) of aliased swigg_module.Pointers
       .Typetab_Pointer;

   -- SwigType_Pointer
   --
   type SwigType_Pointer is access all swigg_module.SwigType;

   -- SwigType_Pointers
   --
   type SwigType_Pointers is
     array
       (interfaces.C.Size_t range <>) of aliased swigg_module.Pointers
       .SwigType_Pointer;

   -- ErrorMessageFormat_Pointer
   --
   type ErrorMessageFormat_Pointer is
     access all swigg_module.ErrorMessageFormat;

   -- ErrorMessageFormat_Pointers
   --
   type ErrorMessageFormat_Pointers is
     array
       (interfaces.C.Size_t range <>) of aliased swigg_module.Pointers
       .ErrorMessageFormat_Pointer;

end swigg_module.Pointers;
