-- This file is generated by SWIG. Please do *not* modify by hand.
--
with interfaces.C;
with interfaces.C.Pointers;

package swigg_module.Wrapper is

   -- Item
   --

   type Item is record
      localh : access swigg_module.Hash;
      def    : access swigg_module.String;
      locals : access swigg_module.String;
      code   : access swigg_module.String;
   end record;

   -- Item_Array
   --
   type Item_Array is
     array (interfaces.C.Size_t range <>) of aliased swigg_module.Wrapper.Item;

   -- Pointer
   --
   package C_Pointers is new interfaces.c.Pointers
     (Index => interfaces.c.size_t, Element => swigg_module.Wrapper.Item,
      element_Array      => swigg_module.Wrapper.Item_Array,
      default_Terminator => (others => <>));

   subtype Pointer is C_Pointers.Pointer;

   -- Pointer_Array
   --
   type Pointer_Array is
     array
       (interfaces.C.Size_t range <>) of aliased swigg_module.Wrapper.Pointer;

   -- Pointer_Pointer
   --
   package C_Pointer_Pointers is new interfaces.c.Pointers
     (Index => interfaces.c.size_t, Element => swigg_module.Wrapper.Pointer,
      element_Array      => swigg_module.Wrapper.Pointer_Array,
      default_Terminator => null);

   subtype Pointer_Pointer is C_Pointer_Pointers.Pointer;

end swigg_module.Wrapper;
