-- This file is generated by SWIG. Please do *not* modify by hand.
--
with Interfaces.C.Pointers;
with Interfaces.C.Strings;
with System;
package simple_example.Pointers is

end simple_example.Pointers;
