-- This file is generated by SWIG. Please do *not* modify by hand.
--
with Interfaces.C;
with Interfaces.C.Pointers;
with Interfaces.C.Strings;
with System;
package simple_example is

   Foo : aliased Long_Float;

private

   pragma Import (C, Foo, "Foo");

end simple_example;
