-- This file is generated by SWIG.
--Please do *not* modify by hand.
--
with Interfaces.C.Pointers;
with Interfaces.C.Strings;
with System;
package template_example.Pointers is

end template_example.Pointers;
