-- This file is generated by SWIG. Do *not* modify by
--hand.
with Interfaces.C;
with Interfaces.C;
package vars_example.Point is

   type Item is record
      x : aliased Interfaces.C.int;
      y : aliased Interfaces.C.int;
   end record;

   type Items is
     array (Interfaces.C.size_t range <>)
            of aliased vars_example.Point.Item;

   type View is access all vars_example.Point.Item;

   function construct return  vars_example.Point.Item;

private

   pragma Import (Cpp, construct, "construct");

end vars_example.Point;
