#!/bin/bash

set -e

#./cleaner

echo
echo Generating bindings.

../../../ada-build/swig4ada  -ada  -I/usr/include   example.i 


echo
echo Pretty printing.
gnatpp  -rnb  -I../../..  *.ads
indent  -sob  -di16       *.c
#indent  -sob  -di16       *.cxx

echo
echo Compiling.
gcc -c *.c
#gnatmake tester -I../../.. -largs example_wrap.o c_example.o

echo
#./cleaner