#!/bin/bash

set -e

#./cleaner

echo
echo Generating bindings.

../../../ada-build/swig4ada  -ada  -I/usr/include   example.i 


echo
echo Pretty printing.

gnatpp --replace               \
       --layout=default        \
       --max-line-length=120   \
       --based-grouping=3      \
       --decimal-grouping=3    \
       --par-threshold=2       \
       --call-threshold=2      \
       -I../../../..           \
       *.ads
       
indent  -sob  -di16  *.c


echo
echo Compiling.

gcc -c *.c
#gnatmake tester -I../../.. -largs example_wrap.o c_example.o

echo
#./cleaner