-- This file is generated by SWIG. Please do *not* modify by hand.
--
with Interfaces.C;
with Interfaces.C.Pointers;
with Interfaces.C.Strings;
with System;
package base is

   -- gdouble
   --
   subtype gdouble is Interfaces.C.double;

   type gdouble_array is
     array (Interfaces.C.size_t range <>) of aliased base.gdouble;

end base;
