-- This file is generated by SWIG. Please do *not* modify by hand.
--
with li_carrays.AB;
with li_carrays.XY;
with interfaces.C;



package li_carrays is





   globalXYArray : aliased li_carrays.XY.Items (0 .. 2);
   globalABArray : aliased li_carrays.AB.Items (0 .. 2);









private



   pragma import (C, globalXYArray, "globalXYArray");
   pragma import (C, globalABArray, "globalABArray");



end li_carrays;
