-- This file is generated by SWIG. Please do not modify by hand.
--
with interfaces.c;
with interfaces.c.strings;
with swig;
with swig_Core.Pointers;

package swigmod is

   -- DoxygenTranslator
   --
   subtype DoxygenTranslator is swig.incomplete_class;

   type DoxygenTranslator_array is
     array (interfaces.C.Size_t range <>) of aliased swigmod.DoxygenTranslator;

   -- Status
   --
   type Status is (Disabled, Experimental, Supported);

   for Status use (Disabled => 0, Experimental => 1, Supported => 2);

   pragma Convention (C, Status);

   type Status_array is
     array (interfaces.C.Size_t range <>) of aliased swigmod.Status;

   NOT_VIRTUAL   : constant                                        := 0;
   PLAIN_VIRTUAL : constant                                        := 1;
   PURE_VIRTUAL  : constant                                        := 2;
   input_file    : aliased swig_Core.Pointers.String_Pointer;
   line_number   : aliased interfaces.c.int;
   start_line    : aliased interfaces.c.int;
   CPlusPlus     : aliased interfaces.c.int;
   Extend        : aliased interfaces.c.int;
   Verbose       : aliased interfaces.c.int;
   IsVirtual     : aliased interfaces.c.int;
   ImportMode    : aliased interfaces.c.int;
   NoExcept      : aliased interfaces.c.int;
   the_Abstract  : aliased interfaces.c.int;
   SmartPointer  : aliased interfaces.c.int;
   SwigRuntime   : aliased interfaces.c.int;
   tab2          : aliased constant interfaces.c.strings.chars_ptr :=
     interfaces.c.strings.new_String ("  ");
   tab4 : aliased constant interfaces.c.strings.chars_ptr :=
     interfaces.c.strings.new_String ("    ");
   tab8 : aliased constant interfaces.c.strings.chars_ptr :=
     interfaces.c.strings.new_String ("        ");

private

   pragma Import (CPP, input_file, "_ZN7swigmod10input_fileE");
   pragma Import (CPP, line_number, "_ZN7swigmod11line_numberE");
   pragma Import (CPP, start_line, "_ZN7swigmod10start_lineE");
   pragma Import (CPP, CPlusPlus, "_ZN7swigmod9CPlusPlusE");
   pragma Import (CPP, Extend, "_ZN7swigmod6ExtendE");
   pragma Import (CPP, Verbose, "_ZN7swigmod7VerboseE");
   pragma Import (CPP, IsVirtual, "_ZN7swigmod9IsVirtualE");
   pragma Import (CPP, ImportMode, "_ZN7swigmod10ImportModeE");
   pragma Import (CPP, NoExcept, "_ZN7swigmod8NoExceptE");
   pragma Import (CPP, the_Abstract, "_ZN7swigmod12the_AbstractE");
   pragma Import (CPP, SmartPointer, "_ZN7swigmod12SmartPointerE");
   pragma Import (CPP, SwigRuntime, "_ZN7swigmod11SwigRuntimeE");

end swigmod;
