-- This file is generated by SWIG. Please do *not* modify by hand.
--
with interfaces.c;
with interfaces.c.strings;
with swig;
with swig.pointers;
with swigg.DohIterator;
with swigg.Language;
with swigg.Pointers;
with swigg.Wrapper;
with swigg.pointer_Pointers;
with interfaces.C;



package swigg.Binding is






   function  DohCheck (ptr : in swigg.Pointers.DOH_Pointer) return interfaces.c.int;

   procedure DohIntern (arg_1 : in swigg.Pointers.DOH_Pointer);

   procedure DohDelete (obj : in swigg.Pointers.DOH_Pointer);

   function  DohCopy (obj : in swigg.Pointers.DOH_Pointer) return swigg.Pointers.DOH_Pointer;

   procedure DohClear (obj : in swigg.Pointers.DOH_Pointer);

   function  DohStr (obj : in swigg.Pointers.DOH_Pointer) return swigg.Pointers.DOH_Pointer;

   function  DohData (obj : in swigg.Pointers.DOH_Pointer) return swig.void_ptr;

   function  DohDump (obj : in swigg.Pointers.DOH_Pointer;
the_out : in swigg.Pointers.DOH_Pointer) return interfaces.c.int;

   function  DohLen (obj : in swigg.Pointers.DOH_Pointer) return interfaces.c.int;

   function  DohHashval (obj : in swigg.Pointers.DOH_Pointer) return interfaces.c.int;

   function  DohCmp (obj1 : in swigg.Pointers.DOH_Pointer;
obj2 : in swigg.Pointers.DOH_Pointer) return interfaces.c.int;

   function  DohEqual (obj1 : in swigg.Pointers.DOH_Pointer;
obj2 : in swigg.Pointers.DOH_Pointer) return interfaces.c.int;

   procedure DohIncref (obj : in swigg.Pointers.DOH_Pointer);

   function  DohGetattr (obj : in swigg.Pointers.DOH_Pointer;
name : in swigg.Pointers.DOH_Pointer) return swigg.Pointers.DOH_Pointer;

   function  DohSetattr (obj : in swigg.Pointers.DOH_Pointer;
name : in swigg.Pointers.DOH_Pointer;
value : in swigg.Pointers.DOH_Pointer) return interfaces.c.int;

   function  DohDelattr (obj : in swigg.Pointers.DOH_Pointer;
name : in swigg.Pointers.DOH_Pointer) return interfaces.c.int;

   function  DohCheckattr (obj : in swigg.Pointers.DOH_Pointer;
name : in swigg.Pointers.DOH_Pointer;
value : in swigg.Pointers.DOH_Pointer) return interfaces.c.int;

   function  DohKeys (obj : in swigg.Pointers.DOH_Pointer) return swigg.Pointers.DOH_Pointer;

   function  DohGetInt (obj : in swigg.Pointers.DOH_Pointer;
name : in swigg.Pointers.DOH_Pointer) return interfaces.c.int;

   procedure DohSetInt (obj : in swigg.Pointers.DOH_Pointer;
name : in swigg.Pointers.DOH_Pointer;
arg_1 : in interfaces.c.int);

   function  DohGetDouble (obj : in swigg.Pointers.DOH_Pointer;
name : in swigg.Pointers.DOH_Pointer) return interfaces.c.double;

   procedure DohSetDouble (obj : in swigg.Pointers.DOH_Pointer;
name : in swigg.Pointers.DOH_Pointer;
arg_1 : in interfaces.c.double);

   function  DohGetChar (obj : in swigg.Pointers.DOH_Pointer;
name : in swigg.Pointers.DOH_Pointer) return interfaces.c.strings.chars_ptr;

   procedure DohSetChar (obj : in swigg.Pointers.DOH_Pointer;
name : in swigg.Pointers.DOH_Pointer;
value : in interfaces.c.strings.chars_ptr);

   function  DohGetFlagAttr (obj : in swigg.Pointers.DOH_Pointer;
name : in swigg.Pointers.DOH_Pointer) return swig.void_ptr;

   function  DohGetFlag (obj : in swigg.Pointers.DOH_Pointer;
name : in swigg.Pointers.DOH_Pointer) return interfaces.c.int;

   procedure DohSetFlagAttr (obj : in swigg.Pointers.DOH_Pointer;
name : in swigg.Pointers.DOH_Pointer;
attr : in swigg.Pointers.DOH_Pointer);

   procedure DohSetFlag (obj : in swigg.Pointers.DOH_Pointer;
name : in swigg.Pointers.DOH_Pointer);

   function  DohGetVoid (obj : in swigg.Pointers.DOH_Pointer;
name : in swigg.Pointers.DOH_Pointer) return swig.void_ptr;

   procedure DohSetVoid (obj : in swigg.Pointers.DOH_Pointer;
name : in swigg.Pointers.DOH_Pointer;
value : in swig.void_ptr);

   function  DohGetitem (obj : in swigg.Pointers.DOH_Pointer;
index : in interfaces.c.int) return swigg.Pointers.DOH_Pointer;

   function  DohSetitem (obj : in swigg.Pointers.DOH_Pointer;
index : in interfaces.c.int;
value : in swigg.Pointers.DOH_Pointer) return interfaces.c.int;

   function  DohDelitem (obj : in swigg.Pointers.DOH_Pointer;
index : in interfaces.c.int) return interfaces.c.int;

   function  DohInsertitem (obj : in swigg.Pointers.DOH_Pointer;
index : in interfaces.c.int;
value : in swigg.Pointers.DOH_Pointer) return interfaces.c.int;

   function  DohDelslice (obj : in swigg.Pointers.DOH_Pointer;
sindex : in interfaces.c.int;
eindex : in interfaces.c.int) return interfaces.c.int;

   function  DohWrite (obj : in swigg.Pointers.DOH_Pointer;
buffer : in swig.void_ptr;
length : in interfaces.c.int) return interfaces.c.int;

   function  DohRead (obj : in swigg.Pointers.DOH_Pointer;
buffer : in swig.void_ptr;
length : in interfaces.c.int) return interfaces.c.int;

   function  DohSeek (obj : in swigg.Pointers.DOH_Pointer;
offset : in interfaces.c.long;
whence : in interfaces.c.int) return interfaces.c.int;

   function  DohTell (obj : in swigg.Pointers.DOH_Pointer) return interfaces.c.long;

   function  DohGetc (obj : in swigg.Pointers.DOH_Pointer) return interfaces.c.int;

   function  DohPutc (ch : in interfaces.c.int;
obj : in swigg.Pointers.DOH_Pointer) return interfaces.c.int;

   function  DohUngetc (ch : in interfaces.c.int;
obj : in swigg.Pointers.DOH_Pointer) return interfaces.c.int;

   function  DohFirst (obj : in swigg.Pointers.DOH_Pointer) return swigg.DohIterator.Item;

   function  DohNext (x : in swigg.DohIterator.Item) return swigg.DohIterator.Item;

   function  DohGetline (obj : in swigg.Pointers.DOH_Pointer) return interfaces.c.int;

   procedure DohSetline (obj : in swigg.Pointers.DOH_Pointer;
line : in interfaces.c.int);

   function  DohGetfile (obj : in swigg.Pointers.DOH_Pointer) return swigg.Pointers.DOH_Pointer;

   procedure DohSetfile (obj : in swigg.Pointers.DOH_Pointer;
file : in swigg.Pointers.DOH_Pointer);

   function  DohReplace (src : in swigg.Pointers.DOH_Pointer;
token : in swigg.Pointers.DOH_Pointer;
rep : in swigg.Pointers.DOH_Pointer;
flags : in interfaces.c.int) return interfaces.c.int;

   procedure DohChop (src : in swigg.Pointers.DOH_Pointer);

   function  DohGetmeta (arg_2_1 : in swigg.Pointers.DOH_Pointer;
arg_2_2 : in swigg.Pointers.DOH_Pointer) return swigg.Pointers.DOH_Pointer;

   function  DohSetmeta (arg_2_1 : in swigg.Pointers.DOH_Pointer;
arg_2_2 : in swigg.Pointers.DOH_Pointer;
value : in swigg.Pointers.DOH_Pointer) return interfaces.c.int;

   function  DohDelmeta (arg_2_1 : in swigg.Pointers.DOH_Pointer;
arg_2_2 : in swigg.Pointers.DOH_Pointer) return interfaces.c.int;

   function  DohPrintf (obj : in swigg.Pointers.DOH_Pointer;
format : in interfaces.c.strings.chars_ptr) return interfaces.c.int;

   function  DohPrintv (obj : in swigg.Pointers.DOH_Pointer) return interfaces.c.int;

   function  DohReadline (the_in : in swigg.Pointers.DOH_Pointer) return swigg.Pointers.DOH_Pointer;

   function  DohIsMapping (obj : in swigg.Pointers.DOH_Pointer) return interfaces.c.int;

   function  DohIsSequence (obj : in swigg.Pointers.DOH_Pointer) return interfaces.c.int;

   function  DohIsString (obj : in swigg.Pointers.DOH_Pointer) return interfaces.c.int;

   function  DohIsFile (obj : in swigg.Pointers.DOH_Pointer) return interfaces.c.int;

   procedure DohSetmark (obj : in swigg.Pointers.DOH_Pointer;
x : in interfaces.c.int);

   function  DohGetmark (obj : in swigg.Pointers.DOH_Pointer) return interfaces.c.int;

   function  DohNewStringEmpty  return swigg.Pointers.DOH_Pointer;

   function  DohNewString (c : in swigg.Pointers.DOH_Pointer) return swigg.Pointers.DOH_Pointer;

   function  DohNewStringWithSize (c : in swigg.Pointers.DOH_Pointer;
len : in interfaces.c.int) return swigg.Pointers.DOH_Pointer;

   function  DohNewStringf (fmt : in swigg.Pointers.DOH_Pointer) return swigg.Pointers.DOH_Pointer;

   function  DohStrcmp (s1 : in swigg.Pointers.DOH_Pointer;
s2 : in swigg.Pointers.DOH_Pointer) return interfaces.c.int;

   function  DohStrncmp (s1 : in swigg.Pointers.DOH_Pointer;
s2 : in swigg.Pointers.DOH_Pointer;
n : in interfaces.c.int) return interfaces.c.int;

   function  DohStrstr (s1 : in swigg.Pointers.DOH_Pointer;
s2 : in swigg.Pointers.DOH_Pointer) return interfaces.c.strings.chars_ptr;

   function  DohStrchr (s1 : in swigg.Pointers.DOH_Pointer;
ch : in interfaces.c.int) return interfaces.c.strings.chars_ptr;

   function  DohNewFile (file : in swigg.Pointers.DOH_Pointer;
mode : in interfaces.c.strings.chars_ptr) return swigg.Pointers.DOH_Pointer;

   function  DohNewFileFromFd (fd : in interfaces.c.int) return swigg.Pointers.DOH_Pointer;

   procedure DohFileErrorDisplay (filename : in swigg.Pointers.DOH_Pointer);

   function  DohClose (file : in swigg.Pointers.DOH_Pointer) return interfaces.c.int;

   function  DohCopyto (input : in swigg.Pointers.DOH_Pointer;
output : in swigg.Pointers.DOH_Pointer) return interfaces.c.int;

   function  DohNewList  return swigg.Pointers.DOH_Pointer;

   function  DohNewHash  return swigg.Pointers.DOH_Pointer;

   function  DohSplit (input : in swigg.Pointers.DOH_Pointer;
ch : in interfaces.c.char;
nsplits : in interfaces.c.int) return swigg.Pointers.DOH_Pointer;

   function  DohSplitLines (input : in swigg.Pointers.DOH_Pointer) return swigg.Pointers.DOH_Pointer;

   procedure DohMemoryDebug ;

   function  DohObjMalloc (the_type : in swigg.Pointers.DohObjInfo_Pointer;
data : in swig.void_ptr) return swigg.Pointers.DOH_Pointer;

   procedure DohObjFree (ptr : in swigg.Pointers.DOH_Pointer);

   function  NewSwigType (typecode : in interfaces.c.int) return swigg.Pointers.SwigType_Pointer;

   function  SwigType_del_element (t : in swigg.Pointers.SwigType_Pointer) return swigg.Pointers.SwigType_Pointer;

   function  SwigType_add_pointer (t : in swigg.Pointers.SwigType_Pointer) return swigg.Pointers.SwigType_Pointer;

   function  SwigType_add_memberpointer (t : in swigg.Pointers.SwigType_Pointer;
qual : in swigg.Pointers.String_or_char_Pointer) return swigg.Pointers.SwigType_Pointer;

   function  SwigType_del_memberpointer (t : in swigg.Pointers.SwigType_Pointer) return swigg.Pointers.SwigType_Pointer;

   function  SwigType_del_pointer (t : in swigg.Pointers.SwigType_Pointer) return swigg.Pointers.SwigType_Pointer;

   function  SwigType_add_array (t : in swigg.Pointers.SwigType_Pointer;
size : in swigg.Pointers.String_or_char_Pointer) return swigg.Pointers.SwigType_Pointer;

   function  SwigType_del_array (t : in swigg.Pointers.SwigType_Pointer) return swigg.Pointers.SwigType_Pointer;

   function  SwigType_pop_arrays (t : in swigg.Pointers.SwigType_Pointer) return swigg.Pointers.SwigType_Pointer;

   function  SwigType_add_reference (t : in swigg.Pointers.SwigType_Pointer) return swigg.Pointers.SwigType_Pointer;

   function  SwigType_del_reference (t : in swigg.Pointers.SwigType_Pointer) return swigg.Pointers.SwigType_Pointer;

   function  SwigType_add_qualifier (t : in swigg.Pointers.SwigType_Pointer;
qual : in swigg.Pointers.String_or_char_Pointer) return swigg.Pointers.SwigType_Pointer;

   function  SwigType_del_qualifier (t : in swigg.Pointers.SwigType_Pointer) return swigg.Pointers.SwigType_Pointer;

   function  SwigType_add_function (t : in swigg.Pointers.SwigType_Pointer;
parms : in swigg.Pointers.ParmList_Pointer) return swigg.Pointers.SwigType_Pointer;

   function  SwigType_add_template (t : in swigg.Pointers.SwigType_Pointer;
parms : in swigg.Pointers.ParmList_Pointer) return swigg.Pointers.SwigType_Pointer;

   function  SwigType_pop_function (t : in swigg.Pointers.SwigType_Pointer) return swigg.Pointers.SwigType_Pointer;

   function  SwigType_function_parms (t : in swigg.Pointers.SwigType_Pointer) return swigg.Pointers.ParmList_Pointer;

   function  SwigType_split (t : in swigg.Pointers.SwigType_Pointer) return swigg.Pointers.List_Pointer;

   function  SwigType_pop (t : in swigg.Pointers.SwigType_Pointer) return swigg.Pointers.String_Pointer;

   procedure SwigType_push (t : in swigg.Pointers.SwigType_Pointer;
s : in swigg.Pointers.SwigType_Pointer);

   function  SwigType_parmlist (p : in swigg.Pointers.SwigType_Pointer) return swigg.Pointers.List_Pointer;

   function  SwigType_parm (p : in swigg.Pointers.String_Pointer) return swigg.Pointers.String_Pointer;

   function  SwigType_str (s : in swigg.Pointers.SwigType_Pointer;
id : in swigg.Pointers.String_or_char_Pointer) return swigg.Pointers.String_Pointer;

   function  SwigType_lstr (s : in swigg.Pointers.SwigType_Pointer;
id : in swigg.Pointers.String_or_char_Pointer) return swigg.Pointers.String_Pointer;

   function  SwigType_rcaststr (s : in swigg.Pointers.SwigType_Pointer;
id : in swigg.Pointers.String_or_char_Pointer) return swigg.Pointers.String_Pointer;

   function  SwigType_lcaststr (s : in swigg.Pointers.SwigType_Pointer;
id : in swigg.Pointers.String_or_char_Pointer) return swigg.Pointers.String_Pointer;

   function  SwigType_manglestr (t : in swigg.Pointers.SwigType_Pointer) return swigg.Pointers.String_Pointer;

   function  SwigType_ltype (t : in swigg.Pointers.SwigType_Pointer) return swigg.Pointers.SwigType_Pointer;

   function  SwigType_ispointer (t : in swigg.Pointers.SwigType_Pointer) return interfaces.c.int;

   function  SwigType_ispointer_return (t : in swigg.Pointers.SwigType_Pointer) return interfaces.c.int;

   function  SwigType_isfunctionpointer (t : in swigg.Pointers.SwigType_Pointer) return interfaces.c.int;

   function  SwigType_ismemberpointer (t : in swigg.Pointers.SwigType_Pointer) return interfaces.c.int;

   function  SwigType_isreference (t : in swigg.Pointers.SwigType_Pointer) return interfaces.c.int;

   function  SwigType_isreference_return (t : in swigg.Pointers.SwigType_Pointer) return interfaces.c.int;

   function  SwigType_isarray (t : in swigg.Pointers.SwigType_Pointer) return interfaces.c.int;

   function  SwigType_prefix_is_simple_1D_array (t : in swigg.Pointers.SwigType_Pointer) return interfaces.c.int;

   function  SwigType_isfunction (t : in swigg.Pointers.SwigType_Pointer) return interfaces.c.int;

   function  SwigType_isqualifier (t : in swigg.Pointers.SwigType_Pointer) return interfaces.c.int;

   function  SwigType_isconst (t : in swigg.Pointers.SwigType_Pointer) return interfaces.c.int;

   function  SwigType_issimple (t : in swigg.Pointers.SwigType_Pointer) return interfaces.c.int;

   function  SwigType_ismutable (t : in swigg.Pointers.SwigType_Pointer) return interfaces.c.int;

   function  SwigType_isvarargs (t : in swigg.Pointers.SwigType_Pointer) return interfaces.c.int;

   function  SwigType_istemplate (t : in swigg.Pointers.SwigType_Pointer) return interfaces.c.int;

   function  SwigType_isenum (t : in swigg.Pointers.SwigType_Pointer) return interfaces.c.int;

   function  SwigType_check_decl (t : in swigg.Pointers.SwigType_Pointer;
decl : in swigg.Pointers.String_or_char_Pointer) return interfaces.c.int;

   function  SwigType_strip_qualifiers (t : in swigg.Pointers.SwigType_Pointer) return swigg.Pointers.SwigType_Pointer;

   function  SwigType_functionpointer_decompose (t : in swigg.Pointers.SwigType_Pointer) return swigg.Pointers.SwigType_Pointer;

   function  SwigType_base (t : in swigg.Pointers.SwigType_Pointer) return swigg.Pointers.String_Pointer;

   function  SwigType_namestr (t : in swigg.Pointers.SwigType_Pointer) return swigg.Pointers.String_Pointer;

   function  SwigType_templateprefix (t : in swigg.Pointers.SwigType_Pointer) return swigg.Pointers.String_Pointer;

   function  SwigType_templatesuffix (t : in swigg.Pointers.SwigType_Pointer) return swigg.Pointers.String_Pointer;

   function  SwigType_templateargs (t : in swigg.Pointers.SwigType_Pointer) return swigg.Pointers.String_Pointer;

   function  SwigType_prefix (t : in swigg.Pointers.SwigType_Pointer) return swigg.Pointers.String_Pointer;

   function  SwigType_array_ndim (t : in swigg.Pointers.SwigType_Pointer) return interfaces.c.int;

   function  SwigType_array_getdim (t : in swigg.Pointers.SwigType_Pointer;
n : in interfaces.c.int) return swigg.Pointers.String_Pointer;

   procedure SwigType_array_setdim (t : in swigg.Pointers.SwigType_Pointer;
n : in interfaces.c.int;
rep : in swigg.Pointers.String_or_char_Pointer);

   function  SwigType_array_type (t : in swigg.Pointers.SwigType_Pointer) return swigg.Pointers.SwigType_Pointer;

   function  SwigType_default (t : in swigg.Pointers.SwigType_Pointer) return swigg.Pointers.String_Pointer;

   procedure SwigType_typename_replace (t : in swigg.Pointers.SwigType_Pointer;
pat : in swigg.Pointers.String_Pointer;
rep : in swigg.Pointers.String_Pointer);

   function  SwigType_alttype (t : in swigg.Pointers.SwigType_Pointer;
ltmap : in interfaces.c.int) return swigg.Pointers.SwigType_Pointer;

   procedure SwigType_typesystem_init ;

   function  SwigType_typedef (the_type : in swigg.Pointers.SwigType_Pointer;
name : in swigg.Pointers.String_or_char_Pointer) return interfaces.c.int;

   function  SwigType_typedef_class (name : in swigg.Pointers.String_or_char_Pointer) return interfaces.c.int;

   function  SwigType_typedef_using (qname : in swigg.Pointers.String_or_char_Pointer) return interfaces.c.int;

   procedure SwigType_inherit (subclass : in swigg.Pointers.String_Pointer;
baseclass : in swigg.Pointers.String_Pointer;
cast : in swigg.Pointers.String_Pointer;
conversioncode : in swigg.Pointers.String_Pointer);

   function  SwigType_issubtype (the_subtype : in swigg.Pointers.SwigType_Pointer;
basetype : in swigg.Pointers.SwigType_Pointer) return interfaces.c.int;

   procedure SwigType_scope_alias (aliasname : in swigg.Pointers.String_Pointer;
t : in swigg.Pointers.Typetab_Pointer);

   procedure SwigType_using_scope (t : in swigg.Pointers.Typetab_Pointer);

   procedure SwigType_new_scope (name : in swigg.Pointers.String_or_char_Pointer);

   procedure SwigType_inherit_scope (scope : in swigg.Pointers.Typetab_Pointer);

   function  SwigType_pop_scope  return swigg.Pointers.Typetab_Pointer;

   function  SwigType_set_scope (h : in swigg.Pointers.Typetab_Pointer) return swigg.Pointers.Typetab_Pointer;

   procedure SwigType_print_scope (t : in swigg.Pointers.Typetab_Pointer);

   function  SwigType_typedef_resolve (t : in swigg.Pointers.SwigType_Pointer) return swigg.Pointers.SwigType_Pointer;

   function  SwigType_typedef_resolve_all (t : in swigg.Pointers.SwigType_Pointer) return swigg.Pointers.SwigType_Pointer;

   function  SwigType_typedef_qualified (t : in swigg.Pointers.SwigType_Pointer) return swigg.Pointers.SwigType_Pointer;

   function  SwigType_istypedef (t : in swigg.Pointers.SwigType_Pointer) return interfaces.c.int;

   function  SwigType_isclass (t : in swigg.Pointers.SwigType_Pointer) return interfaces.c.int;

   procedure SwigType_attach_symtab (syms : in swigg.Pointers.Symtab_Pointer);

   procedure SwigType_remember (t : in swigg.Pointers.SwigType_Pointer);

   procedure SwigType_remember_clientdata (t : in swigg.Pointers.SwigType_Pointer;
clientdata : in swigg.Pointers.String_or_char_Pointer);

   procedure SwigType_remember_mangleddata (mangled : in swigg.Pointers.String_Pointer;
clientdata : in swigg.Pointers.String_or_char_Pointer);

   procedure SwigType_emit_type_table (f_headers : in swigg.Pointers.File_Pointer;
f_table : in swigg.Pointers.File_Pointer);

   function  SwigType_type (t : in swigg.Pointers.SwigType_Pointer) return interfaces.c.int;

   procedure Swig_symbol_init ;

   procedure Swig_symbol_setscopename (name : in swigg.Pointers.String_or_char_Pointer);

   function  Swig_symbol_getscopename  return swigg.Pointers.String_Pointer;

   function  Swig_symbol_qualifiedscopename (symtab : in swigg.Pointers.Symtab_Pointer) return swigg.Pointers.String_Pointer;

   function  Swig_symbol_newscope  return swigg.Pointers.Symtab_Pointer;

   function  Swig_symbol_setscope (arg_1 : in swigg.Pointers.Symtab_Pointer) return swigg.Pointers.Symtab_Pointer;

   function  Swig_symbol_getscope (symname : in swigg.Pointers.String_or_char_Pointer) return swigg.Pointers.Symtab_Pointer;

   function  Swig_symbol_current  return swigg.Pointers.Symtab_Pointer;

   function  Swig_symbol_popscope  return swigg.Pointers.Symtab_Pointer;

   function  Swig_symbol_add (symname : in swigg.Pointers.String_or_char_Pointer;
node : in swigg.Pointers.Node_Pointer) return swigg.Pointers.Node_Pointer;

   procedure Swig_symbol_cadd (symname : in swigg.Pointers.String_or_char_Pointer;
node : in swigg.Pointers.Node_Pointer);

   function  Swig_symbol_clookup (symname : in swigg.Pointers.String_or_char_Pointer;
tab : in swigg.Pointers.Symtab_Pointer) return swigg.Pointers.Node_Pointer;

   function  Swig_symbol_cscope (symname : in swigg.Pointers.String_or_char_Pointer;
tab : in swigg.Pointers.Symtab_Pointer) return swigg.Pointers.Symtab_Pointer;

   function  Swig_symbol_clookup_local (symname : in swigg.Pointers.String_or_char_Pointer;
tab : in swigg.Pointers.Symtab_Pointer) return swigg.Pointers.Node_Pointer;

   function  Swig_symbol_qualified (node : in swigg.Pointers.Node_Pointer) return swigg.Pointers.String_Pointer;

   function  Swig_symbol_isoverloaded (node : in swigg.Pointers.Node_Pointer) return swigg.Pointers.Node_Pointer;

   procedure Swig_symbol_remove (node : in swigg.Pointers.Node_Pointer);

   procedure Swig_symbol_alias (aliasname : in swigg.Pointers.String_or_char_Pointer;
tab : in swigg.Pointers.Symtab_Pointer);

   procedure Swig_symbol_inherit (tab : in swigg.Pointers.Symtab_Pointer);

   function  Swig_symbol_type_qualify (ty : in swigg.Pointers.SwigType_Pointer;
tab : in swigg.Pointers.Symtab_Pointer) return swigg.Pointers.SwigType_Pointer;

   function  Swig_symbol_string_qualify (s : in swigg.Pointers.String_Pointer;
tab : in swigg.Pointers.Symtab_Pointer) return swigg.Pointers.String_Pointer;

   function  Swig_symbol_typedef_reduce (ty : in swigg.Pointers.SwigType_Pointer;
tab : in swigg.Pointers.Symtab_Pointer) return swigg.Pointers.SwigType_Pointer;

   function  Swig_symbol_template_defargs (parms : in swigg.Pointers.Parm_Pointer;
targs : in swigg.Pointers.Parm_Pointer;
tscope : in swigg.Pointers.Symtab_Pointer;
tsdecl : in swigg.Pointers.Symtab_Pointer) return swigg.Pointers.ParmList_Pointer;

   function  Swig_symbol_template_deftype (the_type : in swigg.Pointers.SwigType_Pointer;
tscope : in swigg.Pointers.Symtab_Pointer) return swigg.Pointers.SwigType_Pointer;

   function  Swig_symbol_template_param_eval (p : in swigg.Pointers.SwigType_Pointer;
symtab : in swigg.Pointers.Symtab_Pointer) return swigg.Pointers.SwigType_Pointer;

   function  ParmList_errorstr (arg_1 : in swigg.Pointers.ParmList_Pointer) return swigg.Pointers.String_Pointer;

   function  ParmList_is_compactdefargs (p : in swigg.Pointers.ParmList_Pointer) return interfaces.c.int;

   procedure Swig_name_register (method : in swigg.Pointers.String_or_char_Pointer;
format : in swigg.Pointers.String_or_char_Pointer);

   procedure Swig_name_unregister (method : in swigg.Pointers.String_or_char_Pointer);

   function  Swig_name_mangle (s : in swigg.Pointers.String_or_char_Pointer) return swigg.Pointers.String_Pointer;

   function  Swig_name_wrapper (fname : in swigg.Pointers.String_or_char_Pointer) return swigg.Pointers.String_Pointer;

   function  Swig_name_member (classname : in swigg.Pointers.String_or_char_Pointer;
mname : in swigg.Pointers.String_or_char_Pointer) return swigg.Pointers.String_Pointer;

   function  Swig_name_get (vname : in swigg.Pointers.String_or_char_Pointer) return swigg.Pointers.String_Pointer;

   function  Swig_name_set (vname : in swigg.Pointers.String_or_char_Pointer) return swigg.Pointers.String_Pointer;

   function  Swig_name_construct (classname : in swigg.Pointers.String_or_char_Pointer) return swigg.Pointers.String_Pointer;

   function  Swig_name_copyconstructor (classname : in swigg.Pointers.String_or_char_Pointer) return swigg.Pointers.String_Pointer;

   function  Swig_name_destroy (classname : in swigg.Pointers.String_or_char_Pointer) return swigg.Pointers.String_Pointer;

   function  Swig_name_disown (classname : in swigg.Pointers.String_or_char_Pointer) return swigg.Pointers.String_Pointer;

   procedure Swig_name_namewarn_add (prefix : in swigg.Pointers.String_Pointer;
name : in swigg.Pointers.String_Pointer;
decl : in swigg.Pointers.SwigType_Pointer;
namewrn : in swigg.Pointers.Hash_Pointer);

   function  Swig_name_namewarn_get (n : in swigg.Pointers.Node_Pointer;
prefix : in swigg.Pointers.String_Pointer;
name : in swigg.Pointers.String_Pointer;
decl : in swigg.Pointers.SwigType_Pointer) return swigg.Pointers.Hash_Pointer;

   procedure Swig_name_rename_add (prefix : in swigg.Pointers.String_Pointer;
name : in swigg.Pointers.String_Pointer;
decl : in swigg.Pointers.SwigType_Pointer;
namewrn : in swigg.Pointers.Hash_Pointer;
declaratorparms : in swigg.Pointers.ParmList_Pointer);

   procedure Swig_name_inherit (base : in swigg.Pointers.String_Pointer;
derived : in swigg.Pointers.String_Pointer);

   function  Swig_need_protected (n : in swigg.Pointers.Node_Pointer) return interfaces.c.int;

   function  Swig_need_name_warning (n : in swigg.Pointers.Node_Pointer) return interfaces.c.int;

   function  Swig_need_redefined_warn (a : in swigg.Pointers.Node_Pointer;
b : in swigg.Pointers.Node_Pointer;
InClass : in interfaces.c.int) return interfaces.c.int;

   function  Swig_name_make (n : in swigg.Pointers.Node_Pointer;
prefix : in swigg.Pointers.String_Pointer;
cname : in swigg.Pointers.String_or_char_Pointer;
decl : in swigg.Pointers.SwigType_Pointer;
oldname : in swigg.Pointers.String_Pointer) return swigg.Pointers.String_Pointer;

   function  Swig_name_warning (n : in swigg.Pointers.Node_Pointer;
prefix : in swigg.Pointers.String_Pointer;
name : in swigg.Pointers.String_Pointer;
decl : in swigg.Pointers.SwigType_Pointer) return swigg.Pointers.String_Pointer;

   function  Swig_name_decl (n : in swigg.Pointers.Node_Pointer) return swigg.Pointers.String_Pointer;

   function  Swig_name_fulldecl (n : in swigg.Pointers.Node_Pointer) return swigg.Pointers.String_Pointer;

   procedure Swig_name_object_set (namehash : in swigg.Pointers.Hash_Pointer;
name : in swigg.Pointers.String_or_char_Pointer;
decl : in swigg.Pointers.SwigType_Pointer;
object : in swigg.Pointers.DOH_Pointer);

   function  Swig_name_object_get (namehash : in swigg.Pointers.Hash_Pointer;
prefix : in swigg.Pointers.String_or_char_Pointer;
name : in swigg.Pointers.String_or_char_Pointer;
decl : in swigg.Pointers.SwigType_Pointer) return swigg.Pointers.DOH_Pointer;

   procedure Swig_name_object_inherit (namehash : in swigg.Pointers.Hash_Pointer;
base : in swigg.Pointers.String_Pointer;
derived : in swigg.Pointers.String_Pointer);

   procedure Swig_features_get (features : in swigg.Pointers.Hash_Pointer;
prefix : in swigg.Pointers.String_or_char_Pointer;
name : in swigg.Pointers.String_or_char_Pointer;
decl : in swigg.Pointers.SwigType_Pointer;
n : in swigg.Pointers.Node_Pointer);

   procedure Swig_feature_set (features : in swigg.Pointers.Hash_Pointer;
name : in swigg.Pointers.String_or_char_Pointer;
decl : in swigg.Pointers.SwigType_Pointer;
featurename : in swigg.Pointers.String_or_char_Pointer;
value : in swigg.Pointers.String_Pointer;
featureattribs : in swigg.Pointers.Hash_Pointer);

   function  Swig_copy_string (c : in interfaces.c.strings.chars_ptr) return interfaces.c.strings.chars_ptr;

   procedure Swig_set_fakeversion (version : in interfaces.c.strings.chars_ptr);

   function  Swig_package_version  return interfaces.c.strings.chars_ptr;

   procedure Swig_banner (f : in swigg.Pointers.File_Pointer);

   function  Swig_strip_c_comments (s : in swigg.Pointers.String_Pointer) return swigg.Pointers.String_Pointer;

   function  Swig_string_escape (s : in swigg.Pointers.String_Pointer) return swigg.Pointers.String_Pointer;

   function  Swig_string_mangle (s : in swigg.Pointers.String_Pointer) return swigg.Pointers.String_Pointer;

   procedure Swig_scopename_split (s : in swigg.Pointers.String_Pointer;
prefix : in swigg.pointer_Pointers.String_Pointer_Pointer;
last : in swigg.pointer_Pointers.String_Pointer_Pointer);

   function  Swig_scopename_prefix (s : in swigg.Pointers.String_Pointer) return swigg.Pointers.String_Pointer;

   function  Swig_scopename_last (s : in swigg.Pointers.String_Pointer) return swigg.Pointers.String_Pointer;

   function  Swig_scopename_first (s : in swigg.Pointers.String_Pointer) return swigg.Pointers.String_Pointer;

   function  Swig_scopename_suffix (s : in swigg.Pointers.String_Pointer) return swigg.Pointers.String_Pointer;

   function  Swig_scopename_check (s : in swigg.Pointers.String_Pointer) return interfaces.c.int;

   function  Swig_string_lower (s : in swigg.Pointers.String_Pointer) return swigg.Pointers.String_Pointer;

   function  Swig_string_upper (s : in swigg.Pointers.String_Pointer) return swigg.Pointers.String_Pointer;

   function  Swig_string_title (s : in swigg.Pointers.String_Pointer) return swigg.Pointers.String_Pointer;

   procedure Swig_init ;

   procedure Swig_warn (filename : in interfaces.c.strings.chars_ptr;
line : in interfaces.c.int;
msg : in interfaces.c.strings.chars_ptr);

   function  Swig_value_wrapper_mode (mode : in interfaces.c.int) return interfaces.c.int;

   procedure Swig_warning (num : in interfaces.c.int;
filename : in swigg.Pointers.String_or_char_Pointer;
line : in interfaces.c.int;
fmt : in interfaces.c.strings.chars_ptr);

   procedure Swig_error_file (filename : in swigg.Pointers.String_or_char_Pointer;
line : in interfaces.c.int;
fmt : in interfaces.c.strings.chars_ptr);

   function  Swig_error_count  return interfaces.c.int;

   procedure Swig_error_silent (s : in interfaces.c.int);

   procedure Swig_warnfilter (wlist : in swigg.Pointers.String_or_char_Pointer;
val : in interfaces.c.int);

   procedure Swig_warnall ;

   function  Swig_warn_count  return interfaces.c.int;

   procedure Swig_error_msg_format (format : in swigg.ErrorMessageFormat);

   function  Swig_cparm_name (p : in swigg.Pointers.Parm_Pointer;
i : in interfaces.c.int) return swigg.Pointers.String_Pointer;

   function  Swig_wrapped_var_type (t : in swigg.Pointers.SwigType_Pointer;
varcref : in interfaces.c.int) return swigg.Pointers.String_Pointer;

   function  Swig_cargs (w : in swigg.Wrapper.Pointer;
l : in swigg.Pointers.ParmList_Pointer) return interfaces.c.int;

   function  Swig_cresult (t : in swigg.Pointers.SwigType_Pointer;
name : in swigg.Pointers.String_or_char_Pointer;
decl : in swigg.Pointers.String_or_char_Pointer) return swigg.Pointers.String_Pointer;

   function  Swig_cfunction_call (name : in swigg.Pointers.String_or_char_Pointer;
parms : in swigg.Pointers.ParmList_Pointer) return swigg.Pointers.String_Pointer;

   function  Swig_cconstructor_call (name : in swigg.Pointers.String_or_char_Pointer) return swigg.Pointers.String_Pointer;

   function  Swig_cppconstructor_call (name : in swigg.Pointers.String_or_char_Pointer;
parms : in swigg.Pointers.ParmList_Pointer) return swigg.Pointers.String_Pointer;

   function  Swig_unref_call (n : in swigg.Pointers.Node_Pointer) return swigg.Pointers.String_Pointer;

   function  Swig_ref_call (n : in swigg.Pointers.Node_Pointer;
lname : in swigg.Pointers.String_Pointer) return swigg.Pointers.String_Pointer;

   function  Swig_cdestructor_call (n : in swigg.Pointers.Node_Pointer) return swigg.Pointers.String_Pointer;

   function  Swig_cppdestructor_call (n : in swigg.Pointers.Node_Pointer) return swigg.Pointers.String_Pointer;

   function  Swig_cmemberset_call (name : in swigg.Pointers.String_or_char_Pointer;
the_type : in swigg.Pointers.SwigType_Pointer;
self : in swigg.Pointers.String_or_char_Pointer;
varcref : in interfaces.c.int) return swigg.Pointers.String_Pointer;

   function  Swig_cmemberget_call (name : in swigg.Pointers.String_or_char_Pointer;
t : in swigg.Pointers.SwigType_Pointer;
self : in swigg.Pointers.String_or_char_Pointer;
varcref : in interfaces.c.int) return swigg.Pointers.String_Pointer;

   function  Swig_add_extension_code (n : in swigg.Pointers.Node_Pointer;
function_name : in swigg.Pointers.String_Pointer;
parms : in swigg.Pointers.ParmList_Pointer;
return_type : in swigg.Pointers.SwigType_Pointer;
code : in swigg.Pointers.String_Pointer;
cplusplus : in interfaces.c.int;
self : in swigg.Pointers.String_Pointer) return interfaces.c.int;

   function  Swig_MethodToFunction (n : in swigg.Pointers.Node_Pointer;
classname : in swigg.Pointers.String_Pointer;
flags : in interfaces.c.int;
director_type : in swigg.Pointers.SwigType_Pointer;
is_director : in interfaces.c.int) return interfaces.c.int;

   function  Swig_ConstructorToFunction (n : in swigg.Pointers.Node_Pointer;
classname : in swigg.Pointers.String_Pointer;
none_comparison : in swigg.Pointers.String_Pointer;
director_ctor : in swigg.Pointers.String_Pointer;
cplus : in interfaces.c.int;
flags : in interfaces.c.int) return interfaces.c.int;

   function  Swig_DestructorToFunction (n : in swigg.Pointers.Node_Pointer;
classname : in swigg.Pointers.String_Pointer;
cplus : in interfaces.c.int;
flags : in interfaces.c.int) return interfaces.c.int;

   function  Swig_MembersetToFunction (n : in swigg.Pointers.Node_Pointer;
classname : in swigg.Pointers.String_Pointer;
flags : in interfaces.c.int) return interfaces.c.int;

   function  Swig_MembergetToFunction (n : in swigg.Pointers.Node_Pointer;
classname : in swigg.Pointers.String_Pointer;
flags : in interfaces.c.int) return interfaces.c.int;

   function  Swig_VargetToFunction (n : in swigg.Pointers.Node_Pointer;
flags : in interfaces.c.int) return interfaces.c.int;

   function  Swig_VarsetToFunction (n : in swigg.Pointers.Node_Pointer;
flags : in interfaces.c.int) return interfaces.c.int;

   function  Swig_methodclass (n : in swigg.Pointers.Node_Pointer) return swigg.Pointers.Node_Pointer;

   function  Swig_directorclass (n : in swigg.Pointers.Node_Pointer) return interfaces.c.int;

   function  Swig_directormap (n : in swigg.Pointers.Node_Pointer;
the_type : in swigg.Pointers.String_Pointer) return swigg.Pointers.Node_Pointer;

   procedure Swig_typemap_init ;

   procedure Swig_typemap_register (op : in swigg.Pointers.String_or_char_Pointer;
pattern : in swigg.Pointers.ParmList_Pointer;
code : in swigg.Pointers.String_or_char_Pointer;
locals : in swigg.Pointers.ParmList_Pointer;
kwargs : in swigg.Pointers.ParmList_Pointer);

   function  Swig_typemap_copy (op : in swigg.Pointers.String_or_char_Pointer;
srcpattern : in swigg.Pointers.ParmList_Pointer;
pattern : in swigg.Pointers.ParmList_Pointer) return interfaces.c.int;

   procedure Swig_typemap_clear (op : in swigg.Pointers.String_or_char_Pointer;
pattern : in swigg.Pointers.ParmList_Pointer);

   function  Swig_typemap_apply (srcpat : in swigg.Pointers.ParmList_Pointer;
destpat : in swigg.Pointers.ParmList_Pointer) return interfaces.c.int;

   procedure Swig_typemap_clear_apply (pattern : in swigg.Pointers.ParmList_Pointer);

   procedure Swig_typemap_debug ;

   function  Swig_typemap_search (op : in swigg.Pointers.String_or_char_Pointer;
the_type : in swigg.Pointers.SwigType_Pointer;
pname : in swigg.Pointers.String_or_char_Pointer;
matchtype : in swigg.pointer_Pointers.SwigType_Pointer_Pointer) return swigg.Pointers.Hash_Pointer;

   function  Swig_typemap_search_multi (op : in swigg.Pointers.String_or_char_Pointer;
parms : in swigg.Pointers.ParmList_Pointer;
nmatch : in swig.pointers.int_Pointer) return swigg.Pointers.Hash_Pointer;

   function  Swig_typemap_lookup (op : in swigg.Pointers.String_or_char_Pointer;
n : in swigg.Pointers.Node_Pointer;
lname : in swigg.Pointers.String_or_char_Pointer;
f : in swigg.Wrapper.Pointer) return swigg.Pointers.String_Pointer;

   function  Swig_typemap_lookup_out (op : in swigg.Pointers.String_or_char_Pointer;
n : in swigg.Pointers.Node_Pointer;
lname : in swigg.Pointers.String_or_char_Pointer;
f : in swigg.Wrapper.Pointer;
actioncode : in swigg.Pointers.String_Pointer) return swigg.Pointers.String_Pointer;

   procedure Swig_typemap_attach_kwargs (tm : in swigg.Pointers.Hash_Pointer;
op : in swigg.Pointers.String_or_char_Pointer;
p : in swigg.Pointers.Parm_Pointer);

   procedure Swig_typemap_new_scope ;

   function  Swig_typemap_pop_scope  return swigg.Pointers.Hash_Pointer;

   procedure Swig_typemap_attach_parms (op : in swigg.Pointers.String_or_char_Pointer;
parms : in swigg.Pointers.ParmList_Pointer;
f : in swigg.Wrapper.Pointer);

   procedure Swig_fragment_register (fragment : in swigg.Pointers.Node_Pointer);

   procedure Swig_fragment_emit (name : in swigg.Pointers.String_Pointer);

   function  Swig_director_mode  return interfaces.c.int;

   function  Swig_director_protected_mode  return interfaces.c.int;

   function  Swig_all_protected_mode  return interfaces.c.int;

   procedure Wrapper_director_mode_set (arg_1 : in interfaces.c.int);

   procedure Wrapper_director_protected_mode_set (arg_1 : in interfaces.c.int);

   procedure Wrapper_all_protected_mode_set (arg_1 : in interfaces.c.int);

   procedure SwigType_template_init ;

   function  NewWrapper  return swigg.Wrapper.Pointer;

   procedure DelWrapper (w : in swigg.Wrapper.Pointer);

   procedure Wrapper_compact_print_mode_set (flag : in interfaces.c.int);

   procedure Wrapper_pretty_print (str : in swigg.Pointers.String_Pointer;
f : in swigg.Pointers.File_Pointer);

   procedure Wrapper_compact_print (str : in swigg.Pointers.String_Pointer;
f : in swigg.Pointers.File_Pointer);

   procedure Wrapper_print (w : in swigg.Wrapper.Pointer;
f : in swigg.Pointers.File_Pointer);

   function  Wrapper_add_local (w : in swigg.Wrapper.Pointer;
name : in swigg.Pointers.String_or_char_Pointer;
decl : in swigg.Pointers.String_or_char_Pointer) return interfaces.c.int;

   function  Wrapper_add_localv (w : in swigg.Wrapper.Pointer;
name : in swigg.Pointers.String_or_char_Pointer) return interfaces.c.int;

   function  Wrapper_check_local (w : in swigg.Wrapper.Pointer;
name : in swigg.Pointers.String_or_char_Pointer) return interfaces.c.int;

   function  Wrapper_new_local (w : in swigg.Wrapper.Pointer;
name : in swigg.Pointers.String_or_char_Pointer;
decl : in swigg.Pointers.String_or_char_Pointer) return interfaces.c.strings.chars_ptr;

   function  Preprocessor_expr (s : in swigg.Pointers.String_Pointer;
error : in swig.pointers.int_Pointer) return interfaces.c.int;

   function  Preprocessor_expr_error  return interfaces.c.strings.chars_ptr;

   function  Preprocessor_define (str : in swigg.Pointers.String_or_char_Pointer;
swigmacro : in interfaces.c.int) return swigg.Pointers.Hash_Pointer;

   procedure Preprocessor_undef (name : in swigg.Pointers.String_or_char_Pointer);

   procedure Preprocessor_init ;

   procedure Preprocessor_delete ;

   function  Preprocessor_parse (s : in swigg.Pointers.String_Pointer) return swigg.Pointers.String_Pointer;

   procedure Preprocessor_include_all (arg_1 : in interfaces.c.int);

   procedure Preprocessor_import_all (arg_1 : in interfaces.c.int);

   procedure Preprocessor_ignore_missing (arg_1 : in interfaces.c.int);

   procedure Preprocessor_error_as_warning (arg_1 : in interfaces.c.int);

   function  Preprocessor_depend  return swigg.Pointers.List_Pointer;

   procedure Preprocessor_expr_init ;

   procedure Preprocessor_expr_delete ;

   function  checkAttribute (obj : in swigg.Pointers.Node_Pointer;
name : in swigg.Pointers.String_or_char_Pointer;
value : in swigg.Pointers.String_or_char_Pointer) return interfaces.c.int;

   procedure appendChild (node : in swigg.Pointers.Node_Pointer;
child : in swigg.Pointers.Node_Pointer);

   procedure prependChild (node : in swigg.Pointers.Node_Pointer;
child : in swigg.Pointers.Node_Pointer);

   procedure removeNode (node : in swigg.Pointers.Node_Pointer);

   function  copyNode (node : in swigg.Pointers.Node_Pointer) return swigg.Pointers.Node_Pointer;

   procedure Swig_require (ns : in interfaces.c.strings.chars_ptr;
node : in swigg.Pointers.Node_Pointer);

   procedure Swig_save (ns : in interfaces.c.strings.chars_ptr;
node : in swigg.Pointers.Node_Pointer);

   procedure Swig_restore (node : in swigg.Pointers.Node_Pointer);

   procedure Swig_print_tags (obj : in swigg.Pointers.File_Pointer;
root : in swigg.Pointers.Node_Pointer);

   procedure Swig_print_tree (obj : in swigg.Pointers.Node_Pointer);

   procedure Swig_print_node (obj : in swigg.Pointers.Node_Pointer);

   function  Lang_CurrentClass  return swigg.Pointers.Node_Pointer;

   function  Lang_ClassName  return swigg.Pointers.String_Pointer;

   function  Lang_AddExtern  return interfaces.c.int;

   function  Lang_ForceExtern  return interfaces.c.int;

   function  Lang_first_nontemplate (n : in swigg.Pointers.Node_Pointer) return swigg.Pointers.Node_Pointer;

   function  SWIG_main (arg_3_1 : in interfaces.c.int;
arg_3_2 : in swig.pointers.chars_ptr_Pointer;
arg_3_3 : in swigg.Language.Pointer) return interfaces.c.int;

   procedure emit_parameter_variables (l : in swigg.Pointers.ParmList_Pointer;
f : in swigg.Wrapper.Pointer);

   procedure emit_return_variable (n : in swigg.Pointers.Node_Pointer;
rt : in swigg.Pointers.SwigType_Pointer;
f : in swigg.Wrapper.Pointer);

   procedure SWIG_exit (arg_1 : in interfaces.c.int);

   procedure SWIG_config_file (arg_1 : in swigg.Pointers.String_or_char_Pointer);

   function  SWIG_output_directory  return swigg.Pointers.String_Pointer;

   procedure SWIG_config_cppext (ext : in interfaces.c.strings.chars_ptr);

   procedure SWIG_library_directory (arg_1 : in interfaces.c.strings.chars_ptr);

   function  emit_num_arguments (arg_1 : in swigg.Pointers.ParmList_Pointer) return interfaces.c.int;

   function  emit_num_required (arg_1 : in swigg.Pointers.ParmList_Pointer) return interfaces.c.int;

   function  emit_isvarargs (arg_1 : in swigg.Pointers.ParmList_Pointer) return interfaces.c.int;

   procedure emit_attach_parmmaps (arg_1 : in swigg.Pointers.ParmList_Pointer;
f : in swigg.Wrapper.Pointer);

   procedure emit_mark_varargs (l : in swigg.Pointers.ParmList_Pointer);

   function  emit_action (n : in swigg.Pointers.Node_Pointer) return swigg.Pointers.String_Pointer;

   function  emit_action_code (n : in swigg.Pointers.Node_Pointer;
wrappercode : in swigg.Pointers.String_Pointer;
action : in swigg.Pointers.String_Pointer) return interfaces.c.int;

   procedure Swig_overload_check (n : in swigg.Pointers.Node_Pointer);

   function  Swig_overload_dispatch (n : in swigg.Pointers.Node_Pointer;
fmt : in swigg.Pointers.String_or_char_Pointer;
arg_1 : in swig.pointers.int_Pointer) return swigg.Pointers.String_Pointer;

   function  Swig_overload_dispatch_cast (n : in swigg.Pointers.Node_Pointer;
fmt : in swigg.Pointers.String_or_char_Pointer;
arg_1 : in swig.pointers.int_Pointer) return swigg.Pointers.String_Pointer;

   function  Swig_overload_dispatch_fast (n : in swigg.Pointers.Node_Pointer;
fmt : in swigg.Pointers.String_or_char_Pointer;
arg_1 : in swig.pointers.int_Pointer) return swigg.Pointers.String_Pointer;

   function  cplus_value_type (t : in swigg.Pointers.SwigType_Pointer) return swigg.Pointers.SwigType_Pointer;

   function  Swig_csuperclass_call (base : in swigg.Pointers.String_Pointer;
method : in swigg.Pointers.String_Pointer;
l : in swigg.Pointers.ParmList_Pointer) return swigg.Pointers.String_Pointer;

   function  Swig_class_declaration (n : in swigg.Pointers.Node_Pointer;
name : in swigg.Pointers.String_Pointer) return swigg.Pointers.String_Pointer;

   function  Swig_class_name (n : in swigg.Pointers.Node_Pointer) return swigg.Pointers.String_Pointer;

   function  Swig_method_call (name : in swigg.Pointers.String_or_char_Pointer;
parms : in swigg.Pointers.ParmList_Pointer) return swigg.Pointers.String_Pointer;

   function  Swig_method_decl (rtype : in swigg.Pointers.SwigType_Pointer;
decl : in swigg.Pointers.SwigType_Pointer;
id : in swigg.Pointers.String_or_char_Pointer;
args : in swigg.Pointers.List_Pointer;
strip : in interfaces.c.int;
values : in interfaces.c.int) return swigg.Pointers.String_Pointer;

   function  Swig_director_declaration (n : in swigg.Pointers.Node_Pointer) return swigg.Pointers.String_Pointer;

   procedure Swig_director_emit_dynamic_cast (n : in swigg.Pointers.Node_Pointer;
f : in swigg.Wrapper.Pointer);

   procedure SWIG_typemap_lang (arg_1 : in interfaces.c.strings.chars_ptr);

   function  is_public (n : in swigg.Pointers.Node_Pointer) return interfaces.c.int;

   function  is_private (n : in swigg.Pointers.Node_Pointer) return interfaces.c.int;

   function  is_protected (n : in swigg.Pointers.Node_Pointer) return interfaces.c.int;

   function  is_member_director (parentnode : in swigg.Pointers.Node_Pointer;
member : in swigg.Pointers.Node_Pointer) return interfaces.c.int;

   function  is_member_director (member : in swigg.Pointers.Node_Pointer) return interfaces.c.int;

   function  is_non_virtual_protected_access (n : in swigg.Pointers.Node_Pointer) return interfaces.c.int;

   function  use_naturalvar_mode (n : in swigg.Pointers.Node_Pointer) return interfaces.c.int;

   procedure Wrapper_virtual_elimination_mode_set (arg_1 : in interfaces.c.int);

   procedure Wrapper_fast_dispatch_mode_set (arg_1 : in interfaces.c.int);

   procedure Wrapper_cast_dispatch_mode_set (arg_1 : in interfaces.c.int);

   procedure Wrapper_naturalvar_mode_set (arg_1 : in interfaces.c.int);

   procedure clean_overloaded (n : in swigg.Pointers.Node_Pointer);

   procedure Swig_contracts (n : in swigg.Pointers.Node_Pointer);

   procedure Swig_contract_mode_set (flag : in interfaces.c.int);

   function  Swig_contract_mode_get  return interfaces.c.int;

   procedure Swig_browser (n : in swigg.Pointers.Node_Pointer;
arg_1 : in interfaces.c.int);

   procedure Swig_default_allocators (n : in swigg.Pointers.Node_Pointer);

   procedure Swig_process_types (n : in swigg.Pointers.Node_Pointer);

   function  Swig_add_directory (dirname : in swigg.Pointers.String_or_char_Pointer) return swigg.Pointers.List_Pointer;

   procedure Swig_push_directory (dirname : in swigg.Pointers.String_or_char_Pointer);

   procedure Swig_pop_directory ;

   function  Swig_last_file  return swigg.Pointers.String_Pointer;

   function  Swig_search_path  return swigg.Pointers.List_Pointer;

   function  Swig_open (name : in swigg.Pointers.String_or_char_Pointer) return swig.void_ptr;

   function  Swig_read_file (f : in swig.void_ptr) return swigg.Pointers.String_Pointer;

   function  Swig_include (name : in swigg.Pointers.String_or_char_Pointer) return swigg.Pointers.String_Pointer;

   function  Swig_include_sys (name : in swigg.Pointers.String_or_char_Pointer) return swigg.Pointers.String_Pointer;

   function  Swig_insert_file (name : in swigg.Pointers.String_or_char_Pointer;
outfile : in swigg.Pointers.File_Pointer) return interfaces.c.int;

   procedure Swig_set_push_dir (dopush : in interfaces.c.int);

   function  Swig_get_push_dir  return interfaces.c.int;

   procedure Swig_register_filebyname (filename : in swigg.Pointers.String_or_char_Pointer;
outfile : in swigg.Pointers.File_Pointer);

   function  Swig_filebyname (filename : in swigg.Pointers.String_or_char_Pointer) return swigg.Pointers.File_Pointer;

   function  Swig_file_suffix (filename : in swigg.Pointers.String_or_char_Pointer) return interfaces.c.strings.chars_ptr;

   function  Swig_file_basename (filename : in swigg.Pointers.String_or_char_Pointer) return interfaces.c.strings.chars_ptr;

   function  Swig_file_filename (filename : in swigg.Pointers.String_or_char_Pointer) return interfaces.c.strings.chars_ptr;

   function  Swig_file_dirname (filename : in swigg.Pointers.String_or_char_Pointer) return interfaces.c.strings.chars_ptr;

   procedure Swig_init_args (argc : in interfaces.c.int;
argv : in swig.pointers.chars_ptr_Pointer);

   procedure Swig_mark_arg (n : in interfaces.c.int);

   function  Swig_check_marked (n : in interfaces.c.int) return interfaces.c.int;

   procedure Swig_check_options (check_input : in interfaces.c.int);

   procedure Swig_arg_error ;

   function  runtime_call_Depth  return interfaces.c.int;

   function  String_in (the_string_Array : in swig.pointers.chars_ptr_Pointer;
at_Index : in interfaces.c.int) return interfaces.c.strings.chars_ptr;

   function  c_to_doh_String (c_String : in interfaces.c.strings.chars_ptr) return swigg.Pointers.String_Pointer;

   function  get_attribute (node : in swigg.Pointers.Node_Pointer;
key : in swigg.Pointers.String_Pointer) return swigg.Pointers.Node_Pointer;

   procedure set_attribute (node : in swigg.Pointers.Node_Pointer;
key : in swigg.Pointers.String_Pointer;
value : in swigg.Pointers.String_Pointer);

   function  check_attribute (node : in swigg.Pointers.Node_Pointer;
key : in swigg.Pointers.String_Pointer;
value : in swigg.Pointers.String_Pointer) return swig.bool;

   function  Node_to_CStr (node : in swigg.Pointers.Node_Pointer) return interfaces.c.strings.chars_ptr;

   function  node_Type (node : in swigg.Pointers.Node_Pointer) return swigg.Pointers.DOH_Pointer;

   function  parent_Node (node : in swigg.Pointers.Node_Pointer) return swigg.Pointers.Node_Pointer;

   function  new_File (name : in swigg.Pointers.String_Pointer;
mode : in interfaces.c.strings.chars_ptr) return swigg.Pointers.File_Pointer;

   procedure Print_to (Self : in swigg.Pointers.String_Pointer;
the_Text : in interfaces.c.strings.chars_ptr);

   procedure dump (from : in swigg.Pointers.File_Pointer;
to : in swigg.Pointers.File_Pointer);

   procedure close_File (Self : in swigg.Pointers.File_Pointer);

   procedure doh_replace_All (Self : in swigg.Pointers.DOH_Pointer;
Pattern : in swigg.Pointers.String_Pointer;
Substitute : in swigg.Pointers.String_Pointer);

   function  doh_Copy (Self : in swigg.Pointers.DOH_Pointer) return swigg.Pointers.DOH_Pointer;

   procedure Swig_save_1 (name_Space : in interfaces.c.strings.chars_ptr;
the_Node : in swigg.Pointers.Node_Pointer;
Value : in interfaces.c.strings.chars_ptr);

   procedure Swig_require_2 (name_Space : in interfaces.c.strings.chars_ptr;
the_Node : in swigg.Pointers.Node_Pointer;
Value_1 : in swigg.Pointers.String_Pointer;
Value_2 : in swigg.Pointers.String_Pointer);

   procedure Wrapper_add_local_2 (the_Wrapper : in swigg.Wrapper.Pointer;
Name : in swigg.Pointers.String_or_char_Pointer;
Item_1 : in interfaces.c.strings.chars_ptr;
Item_2 : in interfaces.c.strings.chars_ptr);

   function  first_Child (Self : in swigg.Pointers.Node_Pointer) return swigg.Pointers.Node_Pointer;

   function  next_Sibling (Self : in swigg.Pointers.Node_Pointer) return swigg.Pointers.Node_Pointer;

   procedure exit_with_Fail ;

   function  doh_First (obj : in swigg.Pointers.DOH_Pointer) return swigg.DohIterator.Item;

   function  doh_Next (iter : in swigg.DohIterator.Item) return swigg.DohIterator.Item;

   function  get_Item (Self : in swigg.DohIterator.Item) return swigg.Pointers.DOH_Pointer;

   procedure do_base_top (Self : in swigg.Language.Pointer;
node : in swigg.Pointers.Node_Pointer);

   procedure do_base_enumDeclaration (Self : in swigg.Language.Pointer;
node : in swigg.Pointers.Node_Pointer);

   procedure do_base_classHandler (Self : in swigg.Language.Pointer;
node : in swigg.Pointers.Node_Pointer);

   procedure do_base_memberfunctionHandler (Self : in swigg.Language.Pointer;
node : in swigg.Pointers.Node_Pointer);

   procedure do_base_staticmemberfunctionHandler (Self : in swigg.Language.Pointer;
node : in swigg.Pointers.Node_Pointer);

   procedure do_base_constructorHandler (Self : in swigg.Language.Pointer;
node : in swigg.Pointers.Node_Pointer);

   procedure do_base_destructorHandler (Self : in swigg.Language.Pointer;
node : in swigg.Pointers.Node_Pointer);

   procedure do_base_memberconstantHandler (Self : in swigg.Language.Pointer;
node : in swigg.Pointers.Node_Pointer);

   function  do_base_insertDirective (Self : in swigg.Language.Pointer;
node : in swigg.Pointers.Node_Pointer) return interfaces.c.int;

   function  do_base_typemapDirective (Self : in swigg.Language.Pointer;
node : in swigg.Pointers.Node_Pointer) return interfaces.c.int;

   procedure do_base_namespaceDeclaration (Self : in swigg.Language.Pointer;
node : in swigg.Pointers.Node_Pointer);

   procedure do_base_includeDirective (Self : in swigg.Language.Pointer;
node : in swigg.Pointers.Node_Pointer);









private



   pragma Import (C, DohCheck, "Ada_DohCheck");
   pragma Import (C, DohIntern, "Ada_DohIntern");
   pragma Import (C, DohDelete, "Ada_DohDelete");
   pragma Import (C, DohCopy, "Ada_DohCopy");
   pragma Import (C, DohClear, "Ada_DohClear");
   pragma Import (C, DohStr, "Ada_DohStr");
   pragma Import (C, DohData, "Ada_DohData");
   pragma Import (C, DohDump, "Ada_DohDump");
   pragma Import (C, DohLen, "Ada_DohLen");
   pragma Import (C, DohHashval, "Ada_DohHashval");
   pragma Import (C, DohCmp, "Ada_DohCmp");
   pragma Import (C, DohEqual, "Ada_DohEqual");
   pragma Import (C, DohIncref, "Ada_DohIncref");
   pragma Import (C, DohGetattr, "Ada_DohGetattr");
   pragma Import (C, DohSetattr, "Ada_DohSetattr");
   pragma Import (C, DohDelattr, "Ada_DohDelattr");
   pragma Import (C, DohCheckattr, "Ada_DohCheckattr");
   pragma Import (C, DohKeys, "Ada_DohKeys");
   pragma Import (C, DohGetInt, "Ada_DohGetInt");
   pragma Import (C, DohSetInt, "Ada_DohSetInt");
   pragma Import (C, DohGetDouble, "Ada_DohGetDouble");
   pragma Import (C, DohSetDouble, "Ada_DohSetDouble");
   pragma Import (C, DohGetChar, "Ada_DohGetChar");
   pragma Import (C, DohSetChar, "Ada_DohSetChar");
   pragma Import (C, DohGetFlagAttr, "Ada_DohGetFlagAttr");
   pragma Import (C, DohGetFlag, "Ada_DohGetFlag");
   pragma Import (C, DohSetFlagAttr, "Ada_DohSetFlagAttr");
   pragma Import (C, DohSetFlag, "Ada_DohSetFlag");
   pragma Import (C, DohGetVoid, "Ada_DohGetVoid");
   pragma Import (C, DohSetVoid, "Ada_DohSetVoid");
   pragma Import (C, DohGetitem, "Ada_DohGetitem");
   pragma Import (C, DohSetitem, "Ada_DohSetitem");
   pragma Import (C, DohDelitem, "Ada_DohDelitem");
   pragma Import (C, DohInsertitem, "Ada_DohInsertitem");
   pragma Import (C, DohDelslice, "Ada_DohDelslice");
   pragma Import (C, DohWrite, "Ada_DohWrite");
   pragma Import (C, DohRead, "Ada_DohRead");
   pragma Import (C, DohSeek, "Ada_DohSeek");
   pragma Import (C, DohTell, "Ada_DohTell");
   pragma Import (C, DohGetc, "Ada_DohGetc");
   pragma Import (C, DohPutc, "Ada_DohPutc");
   pragma Import (C, DohUngetc, "Ada_DohUngetc");
   pragma Import (C, DohFirst, "Ada_DohFirst");
   pragma Import (C, DohNext, "Ada_DohNext");
   pragma Import (C, DohGetline, "Ada_DohGetline");
   pragma Import (C, DohSetline, "Ada_DohSetline");
   pragma Import (C, DohGetfile, "Ada_DohGetfile");
   pragma Import (C, DohSetfile, "Ada_DohSetfile");
   pragma Import (C, DohReplace, "Ada_DohReplace");
   pragma Import (C, DohChop, "Ada_DohChop");
   pragma Import (C, DohGetmeta, "Ada_DohGetmeta");
   pragma Import (C, DohSetmeta, "Ada_DohSetmeta");
   pragma Import (C, DohDelmeta, "Ada_DohDelmeta");
   pragma Import (C, DohPrintf, "Ada_DohPrintf");
   pragma Import (C, DohPrintv, "Ada_DohPrintv");
   pragma Import (C, DohReadline, "Ada_DohReadline");
   pragma Import (C, DohIsMapping, "Ada_DohIsMapping");
   pragma Import (C, DohIsSequence, "Ada_DohIsSequence");
   pragma Import (C, DohIsString, "Ada_DohIsString");
   pragma Import (C, DohIsFile, "Ada_DohIsFile");
   pragma Import (C, DohSetmark, "Ada_DohSetmark");
   pragma Import (C, DohGetmark, "Ada_DohGetmark");
   pragma Import (C, DohNewStringEmpty, "Ada_DohNewStringEmpty");
   pragma Import (C, DohNewString, "Ada_DohNewString");
   pragma Import (C, DohNewStringWithSize, "Ada_DohNewStringWithSize");
   pragma Import (C, DohNewStringf, "Ada_DohNewStringf");
   pragma Import (C, DohStrcmp, "Ada_DohStrcmp");
   pragma Import (C, DohStrncmp, "Ada_DohStrncmp");
   pragma Import (C, DohStrstr, "Ada_DohStrstr");
   pragma Import (C, DohStrchr, "Ada_DohStrchr");
   pragma Import (C, DohNewFile, "Ada_DohNewFile");
   pragma Import (C, DohNewFileFromFd, "Ada_DohNewFileFromFd");
   pragma Import (C, DohFileErrorDisplay, "Ada_DohFileErrorDisplay");
   pragma Import (C, DohClose, "Ada_DohClose");
   pragma Import (C, DohCopyto, "Ada_DohCopyto");
   pragma Import (C, DohNewList, "Ada_DohNewList");
   pragma Import (C, DohNewHash, "Ada_DohNewHash");
   pragma Import (C, DohSplit, "Ada_DohSplit");
   pragma Import (C, DohSplitLines, "Ada_DohSplitLines");
   pragma Import (C, DohMemoryDebug, "Ada_DohMemoryDebug");
   pragma Import (C, DohObjMalloc, "Ada_DohObjMalloc");
   pragma Import (C, DohObjFree, "Ada_DohObjFree");
   pragma Import (C, NewSwigType, "Ada_NewSwigType");
   pragma Import (C, SwigType_del_element, "Ada_SwigType_del_element");
   pragma Import (C, SwigType_add_pointer, "Ada_SwigType_add_pointer");
   pragma Import (C, SwigType_add_memberpointer, "Ada_SwigType_add_memberpointer");
   pragma Import (C, SwigType_del_memberpointer, "Ada_SwigType_del_memberpointer");
   pragma Import (C, SwigType_del_pointer, "Ada_SwigType_del_pointer");
   pragma Import (C, SwigType_add_array, "Ada_SwigType_add_array");
   pragma Import (C, SwigType_del_array, "Ada_SwigType_del_array");
   pragma Import (C, SwigType_pop_arrays, "Ada_SwigType_pop_arrays");
   pragma Import (C, SwigType_add_reference, "Ada_SwigType_add_reference");
   pragma Import (C, SwigType_del_reference, "Ada_SwigType_del_reference");
   pragma Import (C, SwigType_add_qualifier, "Ada_SwigType_add_qualifier");
   pragma Import (C, SwigType_del_qualifier, "Ada_SwigType_del_qualifier");
   pragma Import (C, SwigType_add_function, "Ada_SwigType_add_function");
   pragma Import (C, SwigType_add_template, "Ada_SwigType_add_template");
   pragma Import (C, SwigType_pop_function, "Ada_SwigType_pop_function");
   pragma Import (C, SwigType_function_parms, "Ada_SwigType_function_parms");
   pragma Import (C, SwigType_split, "Ada_SwigType_split");
   pragma Import (C, SwigType_pop, "Ada_SwigType_pop");
   pragma Import (C, SwigType_push, "Ada_SwigType_push");
   pragma Import (C, SwigType_parmlist, "Ada_SwigType_parmlist");
   pragma Import (C, SwigType_parm, "Ada_SwigType_parm");
   pragma Import (C, SwigType_str, "Ada_SwigType_str");
   pragma Import (C, SwigType_lstr, "Ada_SwigType_lstr");
   pragma Import (C, SwigType_rcaststr, "Ada_SwigType_rcaststr");
   pragma Import (C, SwigType_lcaststr, "Ada_SwigType_lcaststr");
   pragma Import (C, SwigType_manglestr, "Ada_SwigType_manglestr");
   pragma Import (C, SwigType_ltype, "Ada_SwigType_ltype");
   pragma Import (C, SwigType_ispointer, "Ada_SwigType_ispointer");
   pragma Import (C, SwigType_ispointer_return, "Ada_SwigType_ispointer_return");
   pragma Import (C, SwigType_isfunctionpointer, "Ada_SwigType_isfunctionpointer");
   pragma Import (C, SwigType_ismemberpointer, "Ada_SwigType_ismemberpointer");
   pragma Import (C, SwigType_isreference, "Ada_SwigType_isreference");
   pragma Import (C, SwigType_isreference_return, "Ada_SwigType_isreference_return");
   pragma Import (C, SwigType_isarray, "Ada_SwigType_isarray");
   pragma Import (C, SwigType_prefix_is_simple_1D_array, "Ada_SwigType_prefix_is_simple_1D_array");
   pragma Import (C, SwigType_isfunction, "Ada_SwigType_isfunction");
   pragma Import (C, SwigType_isqualifier, "Ada_SwigType_isqualifier");
   pragma Import (C, SwigType_isconst, "Ada_SwigType_isconst");
   pragma Import (C, SwigType_issimple, "Ada_SwigType_issimple");
   pragma Import (C, SwigType_ismutable, "Ada_SwigType_ismutable");
   pragma Import (C, SwigType_isvarargs, "Ada_SwigType_isvarargs");
   pragma Import (C, SwigType_istemplate, "Ada_SwigType_istemplate");
   pragma Import (C, SwigType_isenum, "Ada_SwigType_isenum");
   pragma Import (C, SwigType_check_decl, "Ada_SwigType_check_decl");
   pragma Import (C, SwigType_strip_qualifiers, "Ada_SwigType_strip_qualifiers");
   pragma Import (C, SwigType_functionpointer_decompose, "Ada_SwigType_functionpointer_decompose");
   pragma Import (C, SwigType_base, "Ada_SwigType_base");
   pragma Import (C, SwigType_namestr, "Ada_SwigType_namestr");
   pragma Import (C, SwigType_templateprefix, "Ada_SwigType_templateprefix");
   pragma Import (C, SwigType_templatesuffix, "Ada_SwigType_templatesuffix");
   pragma Import (C, SwigType_templateargs, "Ada_SwigType_templateargs");
   pragma Import (C, SwigType_prefix, "Ada_SwigType_prefix");
   pragma Import (C, SwigType_array_ndim, "Ada_SwigType_array_ndim");
   pragma Import (C, SwigType_array_getdim, "Ada_SwigType_array_getdim");
   pragma Import (C, SwigType_array_setdim, "Ada_SwigType_array_setdim");
   pragma Import (C, SwigType_array_type, "Ada_SwigType_array_type");
   pragma Import (C, SwigType_default, "Ada_SwigType_default");
   pragma Import (C, SwigType_typename_replace, "Ada_SwigType_typename_replace");
   pragma Import (C, SwigType_alttype, "Ada_SwigType_alttype");
   pragma Import (C, SwigType_typesystem_init, "Ada_SwigType_typesystem_init");
   pragma Import (C, SwigType_typedef, "Ada_SwigType_typedef");
   pragma Import (C, SwigType_typedef_class, "Ada_SwigType_typedef_class");
   pragma Import (C, SwigType_typedef_using, "Ada_SwigType_typedef_using");
   pragma Import (C, SwigType_inherit, "Ada_SwigType_inherit");
   pragma Import (C, SwigType_issubtype, "Ada_SwigType_issubtype");
   pragma Import (C, SwigType_scope_alias, "Ada_SwigType_scope_alias");
   pragma Import (C, SwigType_using_scope, "Ada_SwigType_using_scope");
   pragma Import (C, SwigType_new_scope, "Ada_SwigType_new_scope");
   pragma Import (C, SwigType_inherit_scope, "Ada_SwigType_inherit_scope");
   pragma Import (C, SwigType_pop_scope, "Ada_SwigType_pop_scope");
   pragma Import (C, SwigType_set_scope, "Ada_SwigType_set_scope");
   pragma Import (C, SwigType_print_scope, "Ada_SwigType_print_scope");
   pragma Import (C, SwigType_typedef_resolve, "Ada_SwigType_typedef_resolve");
   pragma Import (C, SwigType_typedef_resolve_all, "Ada_SwigType_typedef_resolve_all");
   pragma Import (C, SwigType_typedef_qualified, "Ada_SwigType_typedef_qualified");
   pragma Import (C, SwigType_istypedef, "Ada_SwigType_istypedef");
   pragma Import (C, SwigType_isclass, "Ada_SwigType_isclass");
   pragma Import (C, SwigType_attach_symtab, "Ada_SwigType_attach_symtab");
   pragma Import (C, SwigType_remember, "Ada_SwigType_remember");
   pragma Import (C, SwigType_remember_clientdata, "Ada_SwigType_remember_clientdata");
   pragma Import (C, SwigType_remember_mangleddata, "Ada_SwigType_remember_mangleddata");
   pragma Import (C, SwigType_emit_type_table, "Ada_SwigType_emit_type_table");
   pragma Import (C, SwigType_type, "Ada_SwigType_type");
   pragma Import (C, Swig_symbol_init, "Ada_Swig_symbol_init");
   pragma Import (C, Swig_symbol_setscopename, "Ada_Swig_symbol_setscopename");
   pragma Import (C, Swig_symbol_getscopename, "Ada_Swig_symbol_getscopename");
   pragma Import (C, Swig_symbol_qualifiedscopename, "Ada_Swig_symbol_qualifiedscopename");
   pragma Import (C, Swig_symbol_newscope, "Ada_Swig_symbol_newscope");
   pragma Import (C, Swig_symbol_setscope, "Ada_Swig_symbol_setscope");
   pragma Import (C, Swig_symbol_getscope, "Ada_Swig_symbol_getscope");
   pragma Import (C, Swig_symbol_current, "Ada_Swig_symbol_current");
   pragma Import (C, Swig_symbol_popscope, "Ada_Swig_symbol_popscope");
   pragma Import (C, Swig_symbol_add, "Ada_Swig_symbol_add");
   pragma Import (C, Swig_symbol_cadd, "Ada_Swig_symbol_cadd");
   pragma Import (C, Swig_symbol_clookup, "Ada_Swig_symbol_clookup");
   pragma Import (C, Swig_symbol_cscope, "Ada_Swig_symbol_cscope");
   pragma Import (C, Swig_symbol_clookup_local, "Ada_Swig_symbol_clookup_local");
   pragma Import (C, Swig_symbol_qualified, "Ada_Swig_symbol_qualified");
   pragma Import (C, Swig_symbol_isoverloaded, "Ada_Swig_symbol_isoverloaded");
   pragma Import (C, Swig_symbol_remove, "Ada_Swig_symbol_remove");
   pragma Import (C, Swig_symbol_alias, "Ada_Swig_symbol_alias");
   pragma Import (C, Swig_symbol_inherit, "Ada_Swig_symbol_inherit");
   pragma Import (C, Swig_symbol_type_qualify, "Ada_Swig_symbol_type_qualify");
   pragma Import (C, Swig_symbol_string_qualify, "Ada_Swig_symbol_string_qualify");
   pragma Import (C, Swig_symbol_typedef_reduce, "Ada_Swig_symbol_typedef_reduce");
   pragma Import (C, Swig_symbol_template_defargs, "Ada_Swig_symbol_template_defargs");
   pragma Import (C, Swig_symbol_template_deftype, "Ada_Swig_symbol_template_deftype");
   pragma Import (C, Swig_symbol_template_param_eval, "Ada_Swig_symbol_template_param_eval");
   pragma Import (C, ParmList_errorstr, "Ada_ParmList_errorstr");
   pragma Import (C, ParmList_is_compactdefargs, "Ada_ParmList_is_compactdefargs");
   pragma Import (C, Swig_name_register, "Ada_Swig_name_register");
   pragma Import (C, Swig_name_unregister, "Ada_Swig_name_unregister");
   pragma Import (C, Swig_name_mangle, "Ada_Swig_name_mangle");
   pragma Import (C, Swig_name_wrapper, "Ada_Swig_name_wrapper");
   pragma Import (C, Swig_name_member, "Ada_Swig_name_member");
   pragma Import (C, Swig_name_get, "Ada_Swig_name_get");
   pragma Import (C, Swig_name_set, "Ada_Swig_name_set");
   pragma Import (C, Swig_name_construct, "Ada_Swig_name_construct");
   pragma Import (C, Swig_name_copyconstructor, "Ada_Swig_name_copyconstructor");
   pragma Import (C, Swig_name_destroy, "Ada_Swig_name_destroy");
   pragma Import (C, Swig_name_disown, "Ada_Swig_name_disown");
   pragma Import (C, Swig_name_namewarn_add, "Ada_Swig_name_namewarn_add");
   pragma Import (C, Swig_name_namewarn_get, "Ada_Swig_name_namewarn_get");
   pragma Import (C, Swig_name_rename_add, "Ada_Swig_name_rename_add");
   pragma Import (C, Swig_name_inherit, "Ada_Swig_name_inherit");
   pragma Import (C, Swig_need_protected, "Ada_Swig_need_protected");
   pragma Import (C, Swig_need_name_warning, "Ada_Swig_need_name_warning");
   pragma Import (C, Swig_need_redefined_warn, "Ada_Swig_need_redefined_warn");
   pragma Import (C, Swig_name_make, "Ada_Swig_name_make");
   pragma Import (C, Swig_name_warning, "Ada_Swig_name_warning");
   pragma Import (C, Swig_name_decl, "Ada_Swig_name_decl");
   pragma Import (C, Swig_name_fulldecl, "Ada_Swig_name_fulldecl");
   pragma Import (C, Swig_name_object_set, "Ada_Swig_name_object_set");
   pragma Import (C, Swig_name_object_get, "Ada_Swig_name_object_get");
   pragma Import (C, Swig_name_object_inherit, "Ada_Swig_name_object_inherit");
   pragma Import (C, Swig_features_get, "Ada_Swig_features_get");
   pragma Import (C, Swig_feature_set, "Ada_Swig_feature_set");
   pragma Import (C, Swig_copy_string, "Ada_Swig_copy_string");
   pragma Import (C, Swig_set_fakeversion, "Ada_Swig_set_fakeversion");
   pragma Import (C, Swig_package_version, "Ada_Swig_package_version");
   pragma Import (C, Swig_banner, "Ada_Swig_banner");
   pragma Import (C, Swig_strip_c_comments, "Ada_Swig_strip_c_comments");
   pragma Import (C, Swig_string_escape, "Ada_Swig_string_escape");
   pragma Import (C, Swig_string_mangle, "Ada_Swig_string_mangle");
   pragma Import (C, Swig_scopename_split, "Ada_Swig_scopename_split");
   pragma Import (C, Swig_scopename_prefix, "Ada_Swig_scopename_prefix");
   pragma Import (C, Swig_scopename_last, "Ada_Swig_scopename_last");
   pragma Import (C, Swig_scopename_first, "Ada_Swig_scopename_first");
   pragma Import (C, Swig_scopename_suffix, "Ada_Swig_scopename_suffix");
   pragma Import (C, Swig_scopename_check, "Ada_Swig_scopename_check");
   pragma Import (C, Swig_string_lower, "Ada_Swig_string_lower");
   pragma Import (C, Swig_string_upper, "Ada_Swig_string_upper");
   pragma Import (C, Swig_string_title, "Ada_Swig_string_title");
   pragma Import (C, Swig_init, "Ada_Swig_init");
   pragma Import (C, Swig_warn, "Ada_Swig_warn");
   pragma Import (C, Swig_value_wrapper_mode, "Ada_Swig_value_wrapper_mode");
   pragma Import (C, Swig_warning, "Ada_Swig_warning");
   pragma Import (C, Swig_error_file, "Ada_Swig_error_file");
   pragma Import (C, Swig_error_count, "Ada_Swig_error_count");
   pragma Import (C, Swig_error_silent, "Ada_Swig_error_silent");
   pragma Import (C, Swig_warnfilter, "Ada_Swig_warnfilter");
   pragma Import (C, Swig_warnall, "Ada_Swig_warnall");
   pragma Import (C, Swig_warn_count, "Ada_Swig_warn_count");
   pragma Import (C, Swig_error_msg_format, "Ada_Swig_error_msg_format");
   pragma Import (C, Swig_cparm_name, "Ada_Swig_cparm_name");
   pragma Import (C, Swig_wrapped_var_type, "Ada_Swig_wrapped_var_type");
   pragma Import (C, Swig_cargs, "Ada_Swig_cargs");
   pragma Import (C, Swig_cresult, "Ada_Swig_cresult");
   pragma Import (C, Swig_cfunction_call, "Ada_Swig_cfunction_call");
   pragma Import (C, Swig_cconstructor_call, "Ada_Swig_cconstructor_call");
   pragma Import (C, Swig_cppconstructor_call, "Ada_Swig_cppconstructor_call");
   pragma Import (C, Swig_unref_call, "Ada_Swig_unref_call");
   pragma Import (C, Swig_ref_call, "Ada_Swig_ref_call");
   pragma Import (C, Swig_cdestructor_call, "Ada_Swig_cdestructor_call");
   pragma Import (C, Swig_cppdestructor_call, "Ada_Swig_cppdestructor_call");
   pragma Import (C, Swig_cmemberset_call, "Ada_Swig_cmemberset_call");
   pragma Import (C, Swig_cmemberget_call, "Ada_Swig_cmemberget_call");
   pragma Import (C, Swig_add_extension_code, "Ada_Swig_add_extension_code");
   pragma Import (C, Swig_MethodToFunction, "Ada_Swig_MethodToFunction");
   pragma Import (C, Swig_ConstructorToFunction, "Ada_Swig_ConstructorToFunction");
   pragma Import (C, Swig_DestructorToFunction, "Ada_Swig_DestructorToFunction");
   pragma Import (C, Swig_MembersetToFunction, "Ada_Swig_MembersetToFunction");
   pragma Import (C, Swig_MembergetToFunction, "Ada_Swig_MembergetToFunction");
   pragma Import (C, Swig_VargetToFunction, "Ada_Swig_VargetToFunction");
   pragma Import (C, Swig_VarsetToFunction, "Ada_Swig_VarsetToFunction");
   pragma Import (C, Swig_methodclass, "Ada_Swig_methodclass");
   pragma Import (C, Swig_directorclass, "Ada_Swig_directorclass");
   pragma Import (C, Swig_directormap, "Ada_Swig_directormap");
   pragma Import (C, Swig_typemap_init, "Ada_Swig_typemap_init");
   pragma Import (C, Swig_typemap_register, "Ada_Swig_typemap_register");
   pragma Import (C, Swig_typemap_copy, "Ada_Swig_typemap_copy");
   pragma Import (C, Swig_typemap_clear, "Ada_Swig_typemap_clear");
   pragma Import (C, Swig_typemap_apply, "Ada_Swig_typemap_apply");
   pragma Import (C, Swig_typemap_clear_apply, "Ada_Swig_typemap_clear_apply");
   pragma Import (C, Swig_typemap_debug, "Ada_Swig_typemap_debug");
   pragma Import (C, Swig_typemap_search, "Ada_Swig_typemap_search");
   pragma Import (C, Swig_typemap_search_multi, "Ada_Swig_typemap_search_multi");
   pragma Import (C, Swig_typemap_lookup, "Ada_Swig_typemap_lookup");
   pragma Import (C, Swig_typemap_lookup_out, "Ada_Swig_typemap_lookup_out");
   pragma Import (C, Swig_typemap_attach_kwargs, "Ada_Swig_typemap_attach_kwargs");
   pragma Import (C, Swig_typemap_new_scope, "Ada_Swig_typemap_new_scope");
   pragma Import (C, Swig_typemap_pop_scope, "Ada_Swig_typemap_pop_scope");
   pragma Import (C, Swig_typemap_attach_parms, "Ada_Swig_typemap_attach_parms");
   pragma Import (C, Swig_fragment_register, "Ada_Swig_fragment_register");
   pragma Import (C, Swig_fragment_emit, "Ada_Swig_fragment_emit");
   pragma Import (C, Swig_director_mode, "Ada_Swig_director_mode");
   pragma Import (C, Swig_director_protected_mode, "Ada_Swig_director_protected_mode");
   pragma Import (C, Swig_all_protected_mode, "Ada_Swig_all_protected_mode");
   pragma Import (C, Wrapper_director_mode_set, "Ada_Wrapper_director_mode_set");
   pragma Import (C, Wrapper_director_protected_mode_set, "Ada_Wrapper_director_protected_mode_set");
   pragma Import (C, Wrapper_all_protected_mode_set, "Ada_Wrapper_all_protected_mode_set");
   pragma Import (C, SwigType_template_init, "Ada_SwigType_template_init");
   pragma Import (C, NewWrapper, "Ada_NewWrapper");
   pragma Import (C, DelWrapper, "Ada_DelWrapper");
   pragma Import (C, Wrapper_compact_print_mode_set, "Ada_Wrapper_compact_print_mode_set");
   pragma Import (C, Wrapper_pretty_print, "Ada_Wrapper_pretty_print");
   pragma Import (C, Wrapper_compact_print, "Ada_Wrapper_compact_print");
   pragma Import (C, Wrapper_print, "Ada_Wrapper_print");
   pragma Import (C, Wrapper_add_local, "Ada_Wrapper_add_local");
   pragma Import (C, Wrapper_add_localv, "Ada_Wrapper_add_localv");
   pragma Import (C, Wrapper_check_local, "Ada_Wrapper_check_local");
   pragma Import (C, Wrapper_new_local, "Ada_Wrapper_new_local");
   pragma Import (C, Preprocessor_expr, "Ada_Preprocessor_expr");
   pragma Import (C, Preprocessor_expr_error, "Ada_Preprocessor_expr_error");
   pragma Import (C, Preprocessor_define, "Ada_Preprocessor_define");
   pragma Import (C, Preprocessor_undef, "Ada_Preprocessor_undef");
   pragma Import (C, Preprocessor_init, "Ada_Preprocessor_init");
   pragma Import (C, Preprocessor_delete, "Ada_Preprocessor_delete");
   pragma Import (C, Preprocessor_parse, "Ada_Preprocessor_parse");
   pragma Import (C, Preprocessor_include_all, "Ada_Preprocessor_include_all");
   pragma Import (C, Preprocessor_import_all, "Ada_Preprocessor_import_all");
   pragma Import (C, Preprocessor_ignore_missing, "Ada_Preprocessor_ignore_missing");
   pragma Import (C, Preprocessor_error_as_warning, "Ada_Preprocessor_error_as_warning");
   pragma Import (C, Preprocessor_depend, "Ada_Preprocessor_depend");
   pragma Import (C, Preprocessor_expr_init, "Ada_Preprocessor_expr_init");
   pragma Import (C, Preprocessor_expr_delete, "Ada_Preprocessor_expr_delete");
   pragma Import (C, checkAttribute, "Ada_checkAttribute");
   pragma Import (C, appendChild, "Ada_appendChild");
   pragma Import (C, prependChild, "Ada_prependChild");
   pragma Import (C, removeNode, "Ada_removeNode");
   pragma Import (C, copyNode, "Ada_copyNode");
   pragma Import (C, Swig_require, "Ada_Swig_require");
   pragma Import (C, Swig_save, "Ada_Swig_save");
   pragma Import (C, Swig_restore, "Ada_Swig_restore");
   pragma Import (C, Swig_print_tags, "Ada_Swig_print_tags");
   pragma Import (C, Swig_print_tree, "Ada_Swig_print_tree");
   pragma Import (C, Swig_print_node, "Ada_Swig_print_node");
   pragma Import (C, Lang_CurrentClass, "Ada_Lang_CurrentClass");
   pragma Import (C, Lang_ClassName, "Ada_Lang_ClassName");
   pragma Import (C, Lang_AddExtern, "Ada_Lang_AddExtern");
   pragma Import (C, Lang_ForceExtern, "Ada_Lang_ForceExtern");
   pragma Import (C, Lang_first_nontemplate, "Ada_Lang_first_nontemplate");
   pragma Import (C, SWIG_main, "Ada_SWIG_main");
   pragma Import (C, emit_parameter_variables, "Ada_emit_parameter_variables");
   pragma Import (C, emit_return_variable, "Ada_emit_return_variable");
   pragma Import (C, SWIG_exit, "Ada_SWIG_exit");
   pragma Import (C, SWIG_config_file, "Ada_SWIG_config_file");
   pragma Import (C, SWIG_output_directory, "Ada_SWIG_output_directory");
   pragma Import (C, SWIG_config_cppext, "Ada_SWIG_config_cppext");
   pragma Import (C, SWIG_library_directory, "Ada_SWIG_library_directory");
   pragma Import (C, emit_num_arguments, "Ada_emit_num_arguments");
   pragma Import (C, emit_num_required, "Ada_emit_num_required");
   pragma Import (C, emit_isvarargs, "Ada_emit_isvarargs");
   pragma Import (C, emit_attach_parmmaps, "Ada_emit_attach_parmmaps");
   pragma Import (C, emit_mark_varargs, "Ada_emit_mark_varargs");
   pragma Import (C, emit_action, "Ada_emit_action");
   pragma Import (C, emit_action_code, "Ada_emit_action_code");
   pragma Import (C, Swig_overload_check, "Ada_Swig_overload_check");
   pragma Import (C, Swig_overload_dispatch, "Ada_Swig_overload_dispatch");
   pragma Import (C, Swig_overload_dispatch_cast, "Ada_Swig_overload_dispatch_cast");
   pragma Import (C, Swig_overload_dispatch_fast, "Ada_Swig_overload_dispatch_fast");
   pragma Import (C, cplus_value_type, "Ada_cplus_value_type");
   pragma Import (C, Swig_csuperclass_call, "Ada_Swig_csuperclass_call");
   pragma Import (C, Swig_class_declaration, "Ada_Swig_class_declaration");
   pragma Import (C, Swig_class_name, "Ada_Swig_class_name");
   pragma Import (C, Swig_method_call, "Ada_Swig_method_call");
   pragma Import (C, Swig_method_decl, "Ada_Swig_method_decl");
   pragma Import (C, Swig_director_declaration, "Ada_Swig_director_declaration");
   pragma Import (C, Swig_director_emit_dynamic_cast, "Ada_Swig_director_emit_dynamic_cast");
   pragma Import (C, SWIG_typemap_lang, "Ada_SWIG_typemap_lang");
   pragma Import (C, is_public, "Ada_is_public");
   pragma Import (C, is_private, "Ada_is_private");
   pragma Import (C, is_protected, "Ada_is_protected");

   function  is_member_director_v1 (parentnode : in swigg.Pointers.Node_Pointer;
member : in swigg.Pointers.Node_Pointer) return interfaces.c.int;



   function  is_member_director (parentnode : in swigg.Pointers.Node_Pointer;
member : in swigg.Pointers.Node_Pointer) return interfaces.c.int
   renames is_member_director_v1;


   pragma Import (C, is_member_director_v1, "Ada_is_member_director__SWIG_0");

   function  is_member_director_v2 (member : in swigg.Pointers.Node_Pointer) return interfaces.c.int;



   function  is_member_director (member : in swigg.Pointers.Node_Pointer) return interfaces.c.int
   renames is_member_director_v2;


   pragma Import (C, is_member_director_v2, "Ada_is_member_director__SWIG_1");
   pragma Import (C, is_non_virtual_protected_access, "Ada_is_non_virtual_protected_access");
   pragma Import (C, use_naturalvar_mode, "Ada_use_naturalvar_mode");
   pragma Import (C, Wrapper_virtual_elimination_mode_set, "Ada_Wrapper_virtual_elimination_mode_set");
   pragma Import (C, Wrapper_fast_dispatch_mode_set, "Ada_Wrapper_fast_dispatch_mode_set");
   pragma Import (C, Wrapper_cast_dispatch_mode_set, "Ada_Wrapper_cast_dispatch_mode_set");
   pragma Import (C, Wrapper_naturalvar_mode_set, "Ada_Wrapper_naturalvar_mode_set");
   pragma Import (C, clean_overloaded, "Ada_clean_overloaded");
   pragma Import (C, Swig_contracts, "Ada_Swig_contracts");
   pragma Import (C, Swig_contract_mode_set, "Ada_Swig_contract_mode_set");
   pragma Import (C, Swig_contract_mode_get, "Ada_Swig_contract_mode_get");
   pragma Import (C, Swig_browser, "Ada_Swig_browser");
   pragma Import (C, Swig_default_allocators, "Ada_Swig_default_allocators");
   pragma Import (C, Swig_process_types, "Ada_Swig_process_types");
   pragma Import (C, Swig_add_directory, "Ada_Swig_add_directory");
   pragma Import (C, Swig_push_directory, "Ada_Swig_push_directory");
   pragma Import (C, Swig_pop_directory, "Ada_Swig_pop_directory");
   pragma Import (C, Swig_last_file, "Ada_Swig_last_file");
   pragma Import (C, Swig_search_path, "Ada_Swig_search_path");
   pragma Import (C, Swig_open, "Ada_Swig_open");
   pragma Import (C, Swig_read_file, "Ada_Swig_read_file");
   pragma Import (C, Swig_include, "Ada_Swig_include");
   pragma Import (C, Swig_include_sys, "Ada_Swig_include_sys");
   pragma Import (C, Swig_insert_file, "Ada_Swig_insert_file");
   pragma Import (C, Swig_set_push_dir, "Ada_Swig_set_push_dir");
   pragma Import (C, Swig_get_push_dir, "Ada_Swig_get_push_dir");
   pragma Import (C, Swig_register_filebyname, "Ada_Swig_register_filebyname");
   pragma Import (C, Swig_filebyname, "Ada_Swig_filebyname");
   pragma Import (C, Swig_file_suffix, "Ada_Swig_file_suffix");
   pragma Import (C, Swig_file_basename, "Ada_Swig_file_basename");
   pragma Import (C, Swig_file_filename, "Ada_Swig_file_filename");
   pragma Import (C, Swig_file_dirname, "Ada_Swig_file_dirname");
   pragma Import (C, Swig_init_args, "Ada_Swig_init_args");
   pragma Import (C, Swig_mark_arg, "Ada_Swig_mark_arg");
   pragma Import (C, Swig_check_marked, "Ada_Swig_check_marked");
   pragma Import (C, Swig_check_options, "Ada_Swig_check_options");
   pragma Import (C, Swig_arg_error, "Ada_Swig_arg_error");
   pragma Import (C, runtime_call_Depth, "Ada_runtime_call_Depth");
   pragma Import (C, String_in, "Ada_String_in");
   pragma Import (C, c_to_doh_String, "Ada_c_to_doh_String");
   pragma Import (C, get_attribute, "Ada_get_attribute");
   pragma Import (C, set_attribute, "Ada_set_attribute");
   pragma Import (C, check_attribute, "Ada_check_attribute");
   pragma Import (C, Node_to_CStr, "Ada_Node_to_CStr");
   pragma Import (C, node_Type, "Ada_node_Type");
   pragma Import (C, parent_Node, "Ada_parent_Node");
   pragma Import (C, new_File, "Ada_new_File");
   pragma Import (C, Print_to, "Ada_Print_to");
   pragma Import (C, dump, "Ada_dump");
   pragma Import (C, close_File, "Ada_close_File");
   pragma Import (C, doh_replace_All, "Ada_doh_replace_All");
   pragma Import (C, doh_Copy, "Ada_doh_Copy");
   pragma Import (C, Swig_save_1, "Ada_Swig_save_1");
   pragma Import (C, Swig_require_2, "Ada_Swig_require_2");
   pragma Import (C, Wrapper_add_local_2, "Ada_Wrapper_add_local_2");
   pragma Import (C, first_Child, "Ada_first_Child");
   pragma Import (C, next_Sibling, "Ada_next_Sibling");
   pragma Import (C, exit_with_Fail, "Ada_exit_with_Fail");
   pragma Import (C, doh_First, "Ada_doh_First");
   pragma Import (C, doh_Next, "Ada_doh_Next");
   pragma Import (C, get_Item, "Ada_get_Item");
   pragma Import (C, do_base_top, "Ada_do_base_top");
   pragma Import (C, do_base_enumDeclaration, "Ada_do_base_enumDeclaration");
   pragma Import (C, do_base_classHandler, "Ada_do_base_classHandler");
   pragma Import (C, do_base_memberfunctionHandler, "Ada_do_base_memberfunctionHandler");
   pragma Import (C, do_base_staticmemberfunctionHandler, "Ada_do_base_staticmemberfunctionHandler");
   pragma Import (C, do_base_constructorHandler, "Ada_do_base_constructorHandler");
   pragma Import (C, do_base_destructorHandler, "Ada_do_base_destructorHandler");
   pragma Import (C, do_base_memberconstantHandler, "Ada_do_base_memberconstantHandler");
   pragma Import (C, do_base_insertDirective, "Ada_do_base_insertDirective");
   pragma Import (C, do_base_typemapDirective, "Ada_do_base_typemapDirective");
   pragma Import (C, do_base_namespaceDeclaration, "Ada_do_base_namespaceDeclaration");
   pragma Import (C, do_base_includeDirective, "Ada_do_base_includeDirective");



end swigg.Binding;
