-- This file is generated by SWIG. Please do *not* modify by hand.
--
with Interfaces.C;
with Swig;
with Interfaces.C;

package swigg.DohBase is

   -- Item
   --

   type Item is record
      data          : aliased Swig.void_ptr;
      the_type      : access swigg.DohObjInfo;
      meta          : aliased Swig.void_ptr;
      flag_intern   : aliased Interfaces.C.unsigned;
      flag_marked   : aliased Interfaces.C.unsigned;
      flag_user     : aliased Interfaces.C.unsigned;
      flag_usermark : aliased Interfaces.C.unsigned;
      refcount      : aliased Interfaces.C.unsigned;
   end record;

   -- Items
   --
   type Items is
     array (Interfaces.C.size_t range <>) of aliased swigg.DohBase.Item;

   -- Pointer
   --
   type Pointer is access all swigg.DohBase.Item;

   -- Pointers
   --
   type Pointers is
     array (Interfaces.C.size_t range <>) of aliased swigg.DohBase.Pointer;

   -- Pointer_Pointer
   --
   type Pointer_Pointer is access all swigg.DohBase.Pointer;

end swigg.DohBase;
