-- This file is generated by SWIG. Please do *not* modify by hand.
--
with Interfaces.C;
with Interfaces.C;

package preproc.TypeNameTraits is

   -- Item
   --

   type Item is record
      val : aliased Interfaces.C.int;
   end record;

   -- Items
   --
   type Items is
     array
       (Interfaces.C.size_t range <>) of aliased preproc.TypeNameTraits.Item;

   -- Pointer
   --
   type Pointer is access all preproc.TypeNameTraits.Item;

   -- Pointers
   --
   type Pointers is
     array
       (Interfaces.C
          .size_t range <>) of aliased preproc.TypeNameTraits.Pointer;

   -- Pointer_Pointer
   --
   type Pointer_Pointer is access all preproc.TypeNameTraits.Pointer;

end preproc.TypeNameTraits;
