/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.36
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
#if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#define SWIGTEMPLATEDISAMBIGUATOR template
#elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#define SWIGTEMPLATEDISAMBIGUATOR template
#else
#define SWIGTEMPLATEDISAMBIGUATOR
#endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
#if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#define SWIGINLINE inline
#else
#define SWIGINLINE
#endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
#if defined(__GNUC__)
#if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#define SWIGUNUSED __attribute__ ((__unused__))
#else
#define SWIGUNUSED
#endif
#elif defined(__ICC)
#define SWIGUNUSED __attribute__ ((__unused__))
#else
#define SWIGUNUSED
#endif
#endif

#ifndef SWIGUNUSEDPARM
#ifdef __cplusplus
#define SWIGUNUSEDPARM(p)
#else
#define SWIGUNUSEDPARM(p) p SWIGUNUSED
#endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
#define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
#define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#ifndef GCC_HASCLASSVISIBILITY
#define GCC_HASCLASSVISIBILITY
#endif
#endif

#ifndef SWIGEXPORT
#if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#if defined(STATIC_LINKED)
#define SWIGEXPORT
#else
#define SWIGEXPORT __declspec(dllexport)
#endif
#else
#if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#define SWIGEXPORT __attribute__ ((visibility("default")))
#else
#define SWIGEXPORT
#endif
#endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
#if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#define SWIGSTDCALL __stdcall
#else
#define SWIGSTDCALL
#endif
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
#define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
#define _SCL_SECURE_NO_DEPRECATE
#endif

#include <stdlib.h>
#include <string.h>
#include <stdio.h>
#if defined(_WIN32) || defined(__CYGWIN32__)
#define DllExport   __declspec( dllexport )
#define SWIGSTDCALL __stdcall
#else
#define DllExport
#define SWIGSTDCALL
#endif

#ifdef __cplusplus
#include <new>
#endif

/* Callback for returning strings to Ada without leaking memory */

typedef char   *(SWIGSTDCALL * SWIG_AdaStringHelperCallback) (const char *);
static SWIG_AdaStringHelperCallback SWIG_ada_string_callback = NULL;

/* probably obsolete ...
#ifdef __cplusplus
extern "C" 
#endif
DllExport void SWIGSTDCALL SWIGRegisterStringCallback_CORE_MODULE(SWIG_AdaStringHelperCallback callback) {
  SWIG_ada_string_callback = callback;
}
*/

/* Contract support */
/*
#define SWIG_contract_assert(nullreturn, expr, msg) if (!(expr)) {SWIG_AdaThrowException(SWIG_AdaArgumentOutOfRangeException, msg); return nullreturn; } else
*/

#define protected public
#define private   public

#ifdef __cplusplus
extern          "C"
{
#endif				/* __cplusplus */
  /* C code */
#ifdef __cplusplus
}
#endif				/* __cplusplus */

int
hello0 ()
{
  return 0;
}

int
hello1 ()
{
  return 1;
}

int
hello2 ()
{
  return 2;
}

int
f (int min)
{
  return min;
}

#define cat(x,y) x ## y

typedef struct EmbeddedDefines
{
  int             dummy;
#define  EMBEDDED_DEFINE 44
#ifdef SWIG
                 %constant EMBEDDED_SWIG_CONSTANT = 55;
#endif
} EmbeddedDefines;

const int       endif = 1;
const int       define = 1;
const int       defined = 1;
int
test (int defined)
{
  return defined;
}

#define TEUCHOS_TYPE_NAME_TRAITS_BUILTIN_TYPE_SPECIALIZATION(TYPE) \
struct TypeNameTraits { \
  int val; \
} \


TEUCHOS_TYPE_NAME_TRAITS_BUILTIN_TYPE_SPECIALIZATION (int);

int
method (struct TypeNameTraits tnt)
{
  return tnt.val;
}

#undef protected
#undef private
#ifdef __cplusplus
extern          "C"
{
#endif
  DllExport int SWIGSTDCALL Ada_hello0 ()
  {
    int             jresult;
    int             result;

                    result = (int) hello0 ();
                    jresult = result;

                    return jresult;

  }

  DllExport int SWIGSTDCALL Ada_hello1 ()
  {
    int             jresult;
    int             result;

    result = (int) hello1 ();
    jresult = result;

    return jresult;

  }

  DllExport int SWIGSTDCALL Ada_hello2 ()
  {
    int             jresult;
    int             result;

    result = (int) hello2 ();
    jresult = result;

    return jresult;

  }

  DllExport int SWIGSTDCALL Ada_f (int jarg1)
  {
    int             jresult;
    int             arg1;
    int             result;

    arg1 = (int) jarg1;

    result = (int) f (arg1);
    jresult = result;

    return jresult;

  }

  DllExport int SWIGSTDCALL Ada_test (int jarg1)
  {
    int             jresult;
    int             arg1;
    int             result;

    arg1 = (int) jarg1;

    result = (int) test (arg1);
    jresult = result;

    return jresult;

  }

  DllExport int SWIGSTDCALL Ada_method (struct TypeNameTraits jarg1)
  {
    int             jresult;
    struct TypeNameTraits arg1;
    int             result;
    struct TypeNameTraits *argp1;

    argp1 = (struct TypeNameTraits *) &jarg1;

    arg1 = *argp1;

    result = (int) method (arg1);
    jresult = result;

    return jresult;

  }

#ifdef __cplusplus
}
#endif
#ifdef __cplusplus
extern          "C"
{
#endif
#ifdef __cplusplus
}
#endif
