-- This file is generated by SWIG. Please do *not* modify by hand.
--
with Interfaces.C;

package preproc.Pointers is

   -- MACROWITHARG_Pointer
   --
   type MACROWITHARG_Pointer is access all preproc.MACROWITHARG;

   -- MACROWITHARG_Pointers
   --
   type MACROWITHARG_Pointers is
     array
       (Interfaces.C
          .size_t range <>) of aliased preproc.Pointers.MACROWITHARG_Pointer;

end preproc.Pointers;
