#!/bin/bash

set -e

#./cleaner

echo
echo Generating bindings.
#../../../ada-build/swig_ada  -ada -c++ -I/usr/include   example.i 
../../../ada-build/swig_ada  -ada  -I/usr/include  -I/usr/local/include  example.i 

echo
echo Pretty printing.
gnatpp  -rnb  -I../../..  *.ads
indent  -sob  -di16       *.c
#indent  -sob  -di16       *.cxx

echo
echo Compiling.
gcc -c *.c
gnatmake tester -I../../.. -largs example_wrap.o c_example.o

echo
#./cleaner