#!/bin/bash

set -e


./cleaner


echo Generating bindings.
#../../../gnat/swig_gnat  -gnat -c++  -cpperraswarn  -I/usr/include   -I/usr/gnat/include/c++/4.3.4/bits   example.i 
../../../gnat/swig_gnat  -gnat -c++  -cpperraswarn  -I/usr/include   llvm.i 


echo Pretty printing.
gnatpp  -rnb  -I../../..   *.ads   -cargs -gnatX -gnat12
indent  -sob  -di16                  *.c



gcc -c *.c
rm *.o
