-- This file is generated by SWIG. Do *not* modify by hand.
with Interfaces.C;
with fun_example.p_f_int_int_ret_int;
package fun_example.Binding is

   funcvar : aliased access fun_example.p_f_int_int_ret_int.Item;

   function do_op
     (arg_2_1 : Interfaces.C.int;
      arg_2_2 : Interfaces.C.int;
      op      : access fun_example.p_f_int_int_ret_int.Item)
      return    Interfaces.C.int;

   function add
     (arg_2_1 : Interfaces.C.int;
      arg_2_2 : Interfaces.C.int)
      return    Interfaces.C.int;

   function sub
     (arg_2_1 : Interfaces.C.int;
      arg_2_2 : Interfaces.C.int)
      return    Interfaces.C.int;

   function mul
     (arg_2_1 : Interfaces.C.int;
      arg_2_2 : Interfaces.C.int)
      return    Interfaces.C.int;

private

   pragma Import (C, funcvar, "funcvar");
   pragma Import (C, do_op, "do_op");
   pragma Import (C, add, "add");
   pragma Import (C, sub, "sub");
   pragma Import (C, mul, "mul");

end fun_example.Binding;
