-- This file is generated by SWIG. Please do *not* modify by hand.
--
with interfaces.c;
with interfaces.C;



package li_carrays.XY is

   -- Item
   -- 

type Item is 
      record
         x : aliased interfaces.c.int;
         y : aliased interfaces.c.int;
      end record;



   -- Items
   -- 
   type Items is array (interfaces.C.Size_t range <>) of aliased li_carrays.XY.Item;



   -- Pointer
   -- 
   type Pointer is access all li_carrays.XY.Item;

   -- Pointers
   -- 
   type Pointers is array (interfaces.C.Size_t range <>) of aliased li_carrays.XY.Pointer;



   -- Pointer_Pointer
   -- 
   type Pointer_Pointer is access all li_carrays.XY.Pointer;










end li_carrays.XY;
