-- This file is generated by SWIG. Please do *not* modify by hand.
--
with interfaces.C;

package swigmod.Pointers is

   -- DoxygenTranslator_Pointer
   --
   type DoxygenTranslator_Pointer is access all swigmod.DoxygenTranslator;

   -- DoxygenTranslator_Pointers
   --
   type DoxygenTranslator_Pointers is
     array
       (interfaces.C.Size_t range <>) of aliased swigmod.Pointers
       .DoxygenTranslator_Pointer;

   -- Status_Pointer
   --
   type Status_Pointer is access all swigmod.Status;

   -- Status_Pointers
   --
   type Status_Pointers is
     array
       (interfaces.C.Size_t range <>) of aliased swigmod.Pointers
       .Status_Pointer;

end swigmod.Pointers;
