#!/bin/bash

set -e


./cleaner


echo Generating bindings.
../../../gnat/swig_gnat  -gnat  -I/usr/include   char_constant.i 


echo Pretty printing.
gnatpp  -rnb  -I../../..   *.ads   -cargs -gnatX -gnat12
indent  -sob  -di16                  *.c



gcc -c *.c
rm *.o
