-- This file is generated by SWIG. Please do *not* modify by hand.
--
with interfaces.C;

package DOHs.Pointers is

   -- DOH_Pointer
   --
   type DOH_Pointer is access all DOHs.DOH;

   -- DOH_Pointers
   --
   type DOH_Pointers is
     array (interfaces.C.Size_t range <>) of aliased DOHs.Pointers.DOH_Pointer;

end DOHs.Pointers;
