-- This file is generated by SWIG. Please do *not* modify by hand.
--
with class_example.Shape;
with interfaces.c;
with interfaces.C;
with System;
private with system.Address_To_Access_Conversions;



package class_example.Square is

   -- Item
   -- 

type Item is new Shape.item with
      record
         width : aliased interfaces.c.double;
      end record;



   -- Items
   -- 
   type Items is array (interfaces.C.Size_t range <>) of aliased class_example.Square.Item;






   function  construct  return class_example.Square.Item'Class;

   function  construct (w : in interfaces.c.double) return class_example.Square.Item'Class;

   function  area (Self : access class_example.Square.Item) return interfaces.c.double;

   function  perimeter (Self : access class_example.Square.Item) return interfaces.c.double;

   procedure destruct_0 (Self : in out class_example.Square.Item);

   procedure destruct (Self : in out class_example.Square.Item);





   -- Pointer
   -- 
   type Pointer is access all class_example.Square.Item;

   -- Pointers
   -- 
   type Pointers is array (interfaces.C.Size_t range <>) of aliased class_example.Square.Pointer;



   -- Pointer_Pointer
   -- 
   type Pointer_Pointer is access all class_example.Square.Pointer;







private



   pragma Import (CPP, Entity => Item);






   function  construct_v1  return class_example.Square.Item'Class;



   function  construct  return class_example.Square.Item'Class
   renames construct_v1;


   pragma cpp_Constructor (construct_v1, "Ada_new_Square__SWIG_0");

   function  construct_v2 (w : in interfaces.c.double) return class_example.Square.Item'Class;



   function  construct (w : in interfaces.c.double) return class_example.Square.Item'Class
   renames construct_v2;


   pragma cpp_Constructor (construct_v2, "Ada_new_Square__SWIG_1");
   pragma Import (CPP, area, "Ada_Square_area");
   pragma Import (CPP, perimeter, "Ada_Square_perimeter");
   pragma Import (CPP, destruct_0, "_ZN6SquareD1Ev");
   pragma Import (CPP, destruct, "_ZN6SquareD1Ev");


   package conversions is new System.Address_To_Access_Conversions (Item);




end class_example.Square;
