-- This file is generated by SWIG. Do *not* modify by hand.
with interfaces.c;
with interfaces.C;
with class_example.Shape;
package class_example.Square is


type Item is new Shape.item with
      record
          null;
      end record;



   type Items is array (interfaces.C.Size_t range <>) of aliased class_example.Square.Item;

   type View is access all class_example.Square.Item'Class ;






   function  construct  return class_example.Square.Item'class;

   procedure destruct (Self : in out class_example.Square.Item);

   function  area (Self : in class_example.Square.Item) return interfaces.c.Double;

   function  perimeter (Self : in class_example.Square.Item) return interfaces.c.Double;





private



   pragma cpp_Class (Entity => Item);








   pragma cpp_Constructor (Entity => construct);

   pragma Import (CPP, construct, "gnat_new_Square");
   pragma cpp_Destructor (Entity => destruct);

   pragma Import (CPP, destruct, "_ZN6SquareD1Ev");
   pragma Import (CPP, area, "Ada_Square_area");
   pragma Import (CPP, perimeter, "Ada_Square_perimeter");

end class_example.Square;
